### ISSUE TITLE
current testing configuration misses dplyr functions in MonetDB.R 1.0.2

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#10]
i also don't think you have a copy_to method, which is basically the first line of the databases vignette?

> yeah we have most of those i think https://dev.monetdb.org/hg/MonetDB/file/tip/clients/R/MonetDB.R/R/dplyr.R

these are in MonetDB.R version 1.0.2 which is not on cran and, since we turned off repo=assets, users would never know about.

even eanthony is not using MonetDB.R 1.0.2 since it's also pulling 1.0.1 from cran:  https://github.com/MonetDB/eanthony/blob/master/packages.R

travis-ci looks like it's also using MonetDB.R 1.0.1, so these functions are totally hidden and untestable for me?

**Comment by hannesmuehleisen** [comment]
copy_to should work, we need it for testing

**Comment by ajdamico** [comment]
what about the others listed here? [1]  i am planning add the dplyr
vignettes to testthat, but want to wait till everything's there

[1]
https://dev.monetdb.org/hg/MonetDB/file/tip/clients/R/MonetDB.R/R/dplyr.R

**Comment by hannesmuehleisen** [comment]
what about those? those are all implemented.

**Comment by ajdamico** [comment]
did you change something?  MonetDB.R 1.0.2 functions were not incorporated into the travis-ci or eanthony testing of dev MonetDBLite

**Comment by hannesmuehleisen** [comment]
Yes it used to install MonetDB.R from assets/R but now it just uses CRAN. Once I make up my mind I’ll have it use the dev version again.

**Comment by ajdamico** [comment]
i need to wait for that to happen before adding dplyr vignettes to testthat

**Comment by hannesmuehleisen** [comment]
I could also just push 1.0.2 to CRAN
