### ISSUE TITLE
logical columns fail to maintain missings

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#106]
col1 row1 should be NA not 0.  sqlite behaves as expected, monetdblite incorrectly coerces the NA to FALSE

	library(DBI)

	sdb <- dbConnect( RSQLite::SQLite() )
	mdb <- dbConnect( MonetDBLite::MonetDBLite() )

	x <- data.frame( col1 = c( NA , TRUE ) , col2 = c( NA , "hello" ) , col3 = c( NA , 1 ) )

	dbWriteTable( mdb , 'x' , x )
	dbReadTable( mdb , 'x' )

	dbWriteTable( sdb , 'x' , x )
	dbReadTable( sdb , 'x' )

**Comment by hannesmuehleisen** [comment]
this goes wrong on the `dbWriteTable` part

**Comment by ajdamico** [comment]
i assume it's somehow related to https://github.com/rstats-db/DBI/issues/152

**Comment by hannesmuehleisen** [comment]
nah this is my fault fixing it atm

**Comment by ajdamico** [comment]
thanks bud
