### ISSUE TITLE
R UDF and dplyr not working dogether?

### ISSUE THREAD

**Issue by hannesmuehleisen** [hannesmuehleisen/MonetDBLite#107]
````
library(MonetDBLite)
library(dplyr)
library(DBI)
 
dbdir <- tempdir()
con <- dbConnect(MonetDBLite())
dbWriteTable(con, "mtcars", mtcars, overwrite = TRUE)
ms <- src_monetdblite(dbdir)
mt <- tbl(ms, "mtcars")
 
dbSendUpdate(con, "CREATE AGGREGATE rapi04(val DOUBLE) RETURNS DOUBLE LANGUAGE R {
    aggregate(val, by=list(aggr_group), FUN=median)$x
};")
 
mt %>% group_by(carb) %>% summarise(rapi04(wt))
````

apparently throws an error.

**Comment by ajdamico** [comment]
slightly more minimal reproducible example?


	library(MonetDBLite)
	library(DBI)
	 
	con <- dbConnect(MonetDBLite())
	dbWriteTable(con, "mtcars", mtcars, overwrite = TRUE)
	 
	dbSendUpdate(con, "CREATE AGGREGATE rapi04(val DOUBLE) RETURNS DOUBLE LANGUAGE R {
		aggregate(val, by=list(aggr_group), FUN=median)$x
	};")

	dbGetQuery( con , "SELECT carb , rapi04( wt ) FROM mtcars GROUP BY carb" )
	# Error in .local(conn, statement, ...) : 
	  # Unable to execute statement 'SELECT carb , rapi04( wt ) FROM mtcars GROUP BY carb'.
	# Server says 'MALException:optimizer.MALoptimizer:Start with inconsistent MAL plan'.

**Comment by hannesmuehleisen** [comment]
great someone broke sh*t

**Comment by hannesmuehleisen** [comment]
no wait there is no R UDFs in MonetDBLite.
