### ISSUE TITLE
dbGetPreparedQuery

### ISSUE THREAD

**Issue by phaverty** [hannesmuehleisen/MonetDBLite#108]
It seems that MonetDBLite does not implement dbGetPreparedQuery.  Is that right?  I have some SQLite applications that could use some speed improvements, but I won't be able to switch over to MonetDBLIte without this feature. Are there plans to implement it?

**Comment by ajdamico** [comment]
hi, `?RSQLite::dbGetPreparedQuery` says these functions are deprecated..

**Comment by phaverty** [comment]
Aha, I hadn't seen that. So the answer is to use dbGetQuery with the
(undocumented in DBI and RSQLite?) bind.data argument.  Thanks!

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com
