### ISSUE TITLE
add global monetdblite shutdown function to the documentation

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#110]
@hannesmuehleisen please close this issue if you think it's a bad idea, otherwise i'll try to write a pull request for you with it at some point?  my use case is whenever a `lodown` function breaks, but i suspect something like this will be useful for other `RSQLite` dependent packages currently on CRAN

if a monetdblite instance gets opened inside a function but then the function breaks, the database might remain open without an available connection `conn` object that can be passed into `dbDisconnect( conn , shutdown = TRUE )`.  a monetdblite-specific global shutdown function would search for the opened monetdblite instance and shut it down without the user needing to figure out the path.  just something simple like `MonetDBLite::monetdblite_shutdown()`.  not sure if this should behave similarly to `closeAllConnections()`

	library(DBI)

	myfun <- 
		function(){
			# open a database in tempdir one
			db <- dbConnect( MonetDBLite::MonetDBLite() , paste0( tempdir() , "one" ) )
			stop("whoops")
		}

	# function leaves connection stranded
	myfun()

	# shutdown everything, allowing the next line to work
	MonetDBLite::monetdblite_shutdown()

	# open a database in tempdir two
	db <- dbConnect( MonetDBLite::MonetDBLite() , paste0( tempdir() , "two" ) )

**Comment by hannesmuehleisen** [comment]
you can just create a new connection to shut down. but we can add the global shutdown method if you like. Hannes

**Comment by ajdamico** [comment]
agree that you can create a new connection, but it's occasionally a pita to
find the db folder.  i'll send a pull request eventually.  thanks

**Comment by hannesmuehleisen** [comment]
Also, this can be done by calling MonetDBLite:::monetdb_embedded_shutdown()

**Comment by ajdamico** [comment]
that's perfect.  i'll figure out where that ought to be documented before `0.4.0`  thanks

**Comment by ajdamico** [comment]
there is now an exported function `monetdblite_shutdown()`

**Comment by ajdamico** [comment]
just opened two pull requests related to this for your review.  thanks again for adding this feature
