### ISSUE TITLE
monet.read.csv fails if csv file is one column of strings

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#112]
i can look closer and attempt a pull request before 0.4.0 if you agree this is a bug?  thanks

	library(DBI)
	library(MonetDBLite)

	tf <- tempfile()

	# one column data.frame
	x <- iris["Species"]

	db <- dbConnect( MonetDBLite() )

	# works
	dbWriteTable( db , 'iris1' , x )

	# fails
	write.csv( x , tf , row.names = FALSE )
	dbWriteTable( db , 'iris2' , tf )

**Comment by hannesmuehleisen** [comment]
sure thats a bug
