### ISSUE TITLE
easy to reproduce low memory segfault (crash) not error on linux

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#116]
on rocks010

needed installs:

	# devtools::install_github( "hannesmuehleisen/MonetDBLite" )
	# devtools::install_github( "krlmlr/ulimit" )

200mb embedded lite crash

	# segfault (crash)
	library(DBI)
	ulimit::memory_limit( 200 )
	db <- dbConnect( MonetDBLite::MonetDBLite() )
	 # *** caught segfault ***
	# address 0x6498, cause 'memory not mapped'

	# Traceback:
	 # 1: .Call("monetdb_startup_R", dir, quiet, getOption("monetdb.squential",     sequential), PACKAGE = libfilename)
	 # 2: monetdb_embedded_startup(embedded, !getOption("monetdb.debug.embedded",     FALSE), getOption("monetdb.sequential", FALSE))
	 # 3: .local(drv, ...)
	 # 4: dbConnect(MonetDBLite::MonetDBLite())
	 # 5: dbConnect(MonetDBLite::MonetDBLite())

	# Possible actions:
	# 1: abort (with core dump, if enabled)
	# 2: normal R exit
	# 3: exit R without saving workspace
	# 4: exit R saving workspace
	# Selection:
	# Selection:

**Comment by hannesmuehleisen** [comment]
Does not crash for me, gives error instead

**Comment by ajdamico** [comment]
i just tested again on `rocks010`  still crash not error..  could you try there?

**Comment by hannesmuehleisen** [comment]
I have.

**Comment by ajdamico** [comment]
bizarre, right?


	[damico@rocks010 ~]$ R

	R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
	Copyright (C) 2016 The R Foundation for Statistical Computing
	Platform: x86_64-redhat-linux-gnu (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	> library(DBI)
	> ulimit::memory_limit( 200 )
	soft hard
	 200  Inf
	> db <- dbConnect( MonetDBLite::MonetDBLite() )

	 *** caught segfault ***
	address 0x6498, cause 'memory not mapped'

	Traceback:
	 1: .Call("monetdb_startup_R", dir, quiet, getOption("monetdb.squential",     se                                                                                                                                                             quential), PACKAGE = libfilename)
	 2: monetdb_embedded_startup(embedded, !getOption("monetdb.debug.embedded",                                                                                                                                                                  FALSE), getOption("monetdb.sequential", FALSE))
	 3: .local(drv, ...)
	 4: dbConnect(MonetDBLite::MonetDBLite())
	 5: dbConnect(MonetDBLite::MonetDBLite())

	Possible actions:
	1: abort (with core dump, if enabled)
	2: normal R exit
	3: exit R without saving workspace
	4: exit R saving workspace
	Selection: 1
	R is aborting now ...
	Segmentation fault (core dumped)
	[damico@rocks010 ~]$ R

**Comment by hannesmuehleisen** [comment]
Latest MonetDBLite?

**Comment by ajdamico** [comment]
just ran `install_github` to get the latest.  still segfault.

**Comment by hannesmuehleisen** [comment]
hmm I had installed with debug flags, trying again without

**Comment by ajdamico** [comment]
thanks

**Comment by hannesmuehleisen** [comment]
seems to work now

**Comment by ajdamico** [comment]
thanks, i'll check

**Comment by ajdamico** [comment]
only errors below `ulimit::memory_limit( 216 )` but no crashes.  thank you!
