### ISSUE TITLE
Reading a CSV file with umlaut characters (Ä, Ö)

### ISSUE THREAD

**Issue by Hergie** [hannesmuehleisen/MonetDBLite#118]
Hello,
I am trying to read in a csv file to the database. The file includes character columns which contain umlauts. 
```
monetdb.read.csv(con, files='file.csv',
                 tablename='FullData', header=T, delim=';',
                 nrow.check = 10000, 
                 colClasses=original.column.classes,
                 encoding="UTF-8") # Valittaa 'line 256163 field 5' ööstä!

```
The transfer of the csv to the database fails with the error:

> SQLException:importTable:Failed to import table line 256163 field 5 'clob' expected in '275553W5141 `<D6>` 555 59153355'',

where the error symbol ``<D6>`` is actually the charater Ö.

I have included ``encoding="UTF-8"`` in the function call but this does not seem to have any effect.

Thanks for help!

**Comment by hannesmuehleisen** [comment]
Which OS is this?

**Comment by Hergie** [comment]
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch``

**Comment by hannesmuehleisen** [comment]
Can you share a sample of the file? And have you tried with the dev version of MonetDBLite?

**Comment by Hergie** [comment]
I'll try the latter. Unfortunately I am not able to share any data.

**Comment by ajdamico** [comment]
hi, i agree this behaves somewhat differently than `read.csv` (example below).  before @hannesmuehleisen releases `0.4.0` i promise to look at this closely and possibly recommend behavior changes.  until that happens, you might need to open up a file connection and destroy those characters manually.  thanks for reporting this

	> my_line <- "Ä"
	> tf <- tempfile()
	> writeLines( my_line , tf )
	> read.csv( tf )
	[1] Ä
	<0 rows> (or 0-length row.names)
	> read.csv( tf , encoding = "UTF-8")
	[1] X.c4.

**Comment by hannesmuehleisen** [comment]
Well you could try to construct some dataset that provokes the same error.

**Comment by ajdamico** [comment]
minimal reproducible example for me to investigate

	library(MonetDBLite)
	library(DBI)
	x <- mtcars
	x[10,1] <- "Ä"
	tf <- tempfile()
	write.csv( x , tf , row.names = F )
	db <- dbConnect( MonetDBLite::MonetDBLite() )

	monetdb.read.csv( db , tf , 'x' , header = TRUE , colClasses = c( "character" , rep( "numeric" , 10 ) ) )

	monetdb.read.csv( db , tf , 'x' , encoding = "UTF-8" , header = TRUE , colClasses = c( "character" , rep( "numeric" , 10 ) ) )

both of the last two lines give
	
	Error in .local(conn, statement, ...) : 
	Unable to execute statement 'COPY OFFSET 2 INTO x FROM 'C:\\Users\\anthonyd\\AppData\\Local\\Temp\\RtmpmAFQk0\\file212447861ea' U...'.
	Server says 'SQLException:importTable:Failed to import table 'x', line 10 field mpg 'clob' expected in '<C4>''.

**Comment by Hergie** [comment]
Ok, thanks for looking at this.

@ajdamico suggested in the mean time to destroy these characters manually. The csv file is 25GB and I don't know how to do this. Any suggestions?

Thanks again!

**Comment by hannesmuehleisen** [comment]
I don't think thats a bug. What you do here is to write the file with the special character to disk using the native windows encoding and then tell MonetDBLite to read them with the different UTF-8 encoding. Suggest either changing your session encoding to UTF-8 as well or set the fileEncoding parameter to write.csv to UTF-8 as well.

**Comment by ajdamico** [comment]
@Hergie you can copy the `ranc_censo` strategy at the bottom of https://github.com/ajdamico/lodown/blob/master/R/censo.R   but it is very slow

@hannesmuehleisen  setting the session encoding doesn't change the error.  should it?

	> options( "encoding" = "UTF-8" )
	> monetdb.read.csv( db , tf , 'x' , encoding = "UTF-8" , header = TRUE , colClasses = c( "character" , rep( "numeric" , 10 ) ) )
	Error in .local(conn, statement, ...) : 
	  Unable to execute statement 'COPY OFFSET 2 INTO x FROM 'C:\\Users\\anthonyd\\AppData\\Local\\Temp\\RtmpqQ7W9v\\file1598340531fd' ...'.
	Server says 'SQLException:importTable:Failed to import table 'x', line 10 field mpg 'clob' expected in '<C4>''.
	In addition: Warning messages:
	1: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
	  invalid input found on input connection 'C:\Users\anthonyd\AppData\Local\Temp\RtmpqQ7W9v\file1598340531fd'
	2: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
	  EOF within quoted string

**Comment by Hergie** [comment]
It also fails with the same error message if I omit the encoding argument
from the original function call.
