### ISSUE TITLE
nppes on windows failure information at shutdown=TRUE?

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#12]
most recent two lab07win nppes runs have failed [1] [2]

i ran the code in nppes-setup.R [3] eight times:

4 of 4 runs in Rterm.exe, the program ran through without any problem

3 of 4 runs in Rgui.exe, the console disappeared

[1] http://monetdb.cwi.nl/testweb/web/eanthony/lab07win/1463815347/nppes.log
[2] http://monetdb.cwi.nl/testweb/web/eanthony/lab07win/1463160515/nppes.log
[3] https://github.com/MonetDB/eanthony/blob/master/nppes-setup.R

**Comment by hannesmuehleisen** [comment]
![wat8](https://cloud.githubusercontent.com/assets/227792/15465370/77d57aba-20d4-11e6-9460-8e39322ce68b.jpg)

**Comment by ajdamico** [comment]
hahaha yup

**Comment by hannesmuehleisen** [comment]
can you check whether this is still an issue?

**Comment by hannesmuehleisen** [comment]
just tried this and it worked on Windows

**Comment by ajdamico** [comment]
out of 8 consoles: 5 failed, 3 passed

**Comment by ajdamico** [comment]
if you still want to push to cran soon, any reason not to move this to 0.4.0?

**Comment by hannesmuehleisen** [comment]
yeah we might postpone this...

**Comment by hannesmuehleisen** [comment]
Please retry if possible

**Comment by ajdamico** [comment]
out of 4 consoles: 1 failed, 3 passed  :(

**Comment by hannesmuehleisen** [comment]
any output?

**Comment by ajdamico** [comment]
never-- rgui always disappears

**Comment by hannesmuehleisen** [comment]
so less crashed this time? :)

**Comment by ajdamico** [comment]
:P

**Comment by hannesmuehleisen** [comment]
ok moving this to next release

**Comment by ajdamico** [comment]
closing because obsolete at this point, i think?
