### ISSUE TITLE
Problems with installation with aggressive compiler flags

### ISSUE THREAD

**Issue by dselivanov** [hannesmuehleisen/MonetDBLite#120]
**gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, R 3.3.3**

With `-O3` installs just fine.

With `-O3 -ffast-math -march=native -mavx -fopenmp` fails with:

> ** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'MonetDBLite', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/dselivanov/R/x86_64-pc-linux-gnu-library/3.3/MonetDBLite/libs/libmonetdb5.so':
  /home/dselivanov/R/x86_64-pc-linux-gnu-library/3.3/MonetDBLite/libs/libmonetdb5.so: undefined symbol: _ZGVdN8vv___powf_finite
Error: loading failed
Execution halted
ERROR: loading failed
removing ‘/home/dselivanov/R/x86_64-pc-linux-gnu-library/3.3/MonetDBLite’
Error: Command failed (1)

**Comment by hannesmuehleisen** [comment]
Which one of these flags makes it break?

**Comment by dselivanov** [comment]
Will clarify, will take some time. Interestingly it compiles fine with those flags on local OS X machine with `clang-3.8`, but fails on on ubuntu 16.04 on AWS machine with `gcc-5.4`.

**Comment by dselivanov** [comment]
`-fopenmp` was the source of the problem. I had it in `CXX1XFLAGS`, `CXXFLAGS`, `CFLAGS` in my `~/.R/Makevars`.  After I moved it to `PKG_CFLAGS` and `PKG_CXXFLAGS` error gone. So I think that was my mistake. Closing, sorry for bothering.

```
CXX1XFLAGS += -O3 -ffast-math -march=native -mavx
CXXFLAGS   += -O3 -ffast-math -march=native -mavx
CFLAGS     += -O3 -ffast-math -march=native -mavx

PKG_CFLAGS += -fopenmp
PKG_CXXFLAGS += -fopenmp
```
