### ISSUE TITLE
pip install failing

### ISSUE THREAD

**Issue by Teva** [hannesmuehleisen/MonetDBLite#123]
running `pip install monetdblite ` returns the following :

  

> Collecting monetdblite
>   Using cached monetdblite-0.1.9.tar.gz
>     Complete output from command python setup.py egg_info:
>     Building MonetDBLite from source requires NumPy to be installed.
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-IeyfED/monetdblite/

**Comment by hannesmuehleisen** [comment]
Maybe install numpy as it says?

**Comment by Teva** [comment]
I have anaconda installed and already have numpy installed.

**Comment by Teva** [comment]
oddly enough when trying to run pip install numpy I also have an error

> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zsxuWR/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vjfcbC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-zsxuWR/numpy/

Seems my error has nothing to do with monetdblite but more with setuptools.

thank you for the commitment @hannesmuehleisen

**Comment by Teva** [comment]
well monetdblite is now installed, however after importing the module `import monetdblite` I am exited from the python env with the following message : 

> Segmentation fault: 11

**Comment by hannesmuehleisen** [comment]
This sounds like different python versions, broken numpy installation, different library paths etc. It should not crash regardless though. @Mytherin perhaps have a look?

**Comment by hannesmuehleisen** [comment]
Is this still an issue?

**Comment by Teva** [comment]
Hello,

I confirm this was due to my personal setup and Path configuration, it works perfectly in other systems (tested and ok on Ubuntu to check if this was my mac machine or the monetdblite package).

Thank you for the help.

**Comment by hannesmuehleisen** [comment]
Great, closing here.
