### ISSUE TITLE
dbSendUpdateAsync

### ISSUE THREAD

**Issue by bhaskarvk** [hannesmuehleisen/MonetDBLite#124]
I'm seeing some errors when I use `dbSendUpdateAsync`.

w/o async

```r
dbSendUpdate(
     con,
     "INSERT INTO results (run_id, domain, status, headers) VALUES (?, ?, ?, ?)",
             run$id, req$url, req$status_code, headers)
```

The above succeeds, but the below fails with the error shown 

```r
dbSendUpdateAsync(
     con,
     "INSERT INTO results (run_id, domain, status, headers) VALUES (?, ?, ?, ?)",
             run$id, req$url, req$status_code, headers)
```

```
Error in .local(conn, statement, ...) : 
  Unable to execute statement 'INSERT INTO results (run_id, domain, status, headers) VALUES (TRUE, ?, ?, ?)'.
Server says 'ParseException:SQLparser:SELECT: parameters ('?') not allowed in normal queries, use PREPARE'.
```

What's interesting is if I call `dbSendUpdate` with `async=TRUE`, that works.

```r
dbSendUpdate(
     con,
     "INSERT INTO results (run_id, domain, status, headers) VALUES (?, ?, ?, ?)",
             run$id, req$url, req$status_code, headers, async=TRUE)
```

Any clues what could be the issue with `dbSendUpdateAsync` ? Also how is `dbSendUpdateAsync` different from `dbSendUpdate(..., async=TRUE)`.

Here's a full reproducible code for the error

```r
library(DBI)
library(MonetDBLite)

dbdir <- file.path( tempdir() , "sendupdate" )
con <- dbConnect(MonetDBLite::MonetDBLite(), dbdir)

# create table
dbSendUpdate(con, "CREATE TABLE foo(a INT,b VARCHAR(100))")
# insert value, bind parameters to placeholders in statement
dbSendUpdate(con, "INSERT INTO foo VALUES(?,?)", 1, "foo")
dbSendUpdateAsync(con, "INSERT INTO foo VALUES(?,?)", 2, "bar") # THIS FAILS
dbSendUpdate(con, "INSERT INTO foo VALUES(?,?)", 3, "baz", async=TRUE)

print(dbGetQuery(con, "SELECT * FROM foo"))

dbDisconnect(con,shutdown=TRUE)

```

**Comment by hannesmuehleisen** [comment]
What are you using `dbSendUpdateAsync` for? Its intended to be used in garbage collection of DB-backed objects like in the (unmaintained) `sqlsurvey` package. Regardless, fixed.

**Comment by bhaskarvk** [comment]
I am using it in conjunction with curl package to fetch data simultaneously from web and insert it into monetdb as it arrives. https://cran.r-project.org/web/packages/curl/vignettes/intro.html#async_requests

So my handler function gets called for each new completed request which can happen asynchronously and hence I need to do async upload to monetdb.

Thanks for fixing it so quickly and a great package!

**Comment by hannesmuehleisen** [comment]
I think it makes little sense to use dbSendUpdate with the async option for MonetDBLite even in this case. Suggest you switch to the standard DBI ways. We are going to remove dbSendUpdate in the 0.4.0 version I think.
