### ISSUE TITLE
MALException:opt.remap:Function 'mkey.hash' not defined

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#126]
see 2017-03-18 comment

https://www.monetdb.org/bugzilla/show_bug.cgi?id=6211

if that doesn't solve it, we'll need some other way to test

**Comment by hannesmuehleisen** [comment]
honestly have no idea how to progress here.

**Comment by ajdamico** [comment]
this still fails with today's `Jul2017Lite-R` branch.  we need to run the same code in the current dev branch of mserver to resolve whether this bug is mserver or lite.  thanks

**Comment by hannesmuehleisen** [comment]
You can download the dev version from here http://monetdb.cwi.nl/testweb/web/63930:16a4efa7b3dc/MonetDB5-SQL-Installer-x86_64-16a4efa7b3dc.msi

**Comment by ajdamico** [comment]
minimal reproducible example triggering bug on monetdblite but not mserver..  also prints EXPLAIN and PLAN to home directory, thanks



	# large set of UNION ALL commands
	union_all_columns <- 

		c(
			"NULL AS group_col", 
			"NULL AS group_col", 
			"NULL AS group_col", 
			"NULL AS group_col", 
			"NULL AS group_col", 
			"NULL AS group_col", 
			"NULL AS group_col", 
			"NULL AS group_col", 
			"NULL AS group_col", 
			" ( CASE WHEN between_value THEN 'YES' WHEN NOT between_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN between_value THEN 'YES' WHEN NOT between_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN between_value THEN 'YES' WHEN NOT between_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN between_value THEN 'YES' WHEN NOT between_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN between_value THEN 'YES' WHEN NOT between_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN between_value THEN 'YES' WHEN NOT between_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN between_value THEN 'YES' WHEN NOT between_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN between_value THEN 'YES' WHEN NOT between_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN high_value THEN 'YES' WHEN NOT high_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN high_value THEN 'YES' WHEN NOT high_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN high_value THEN 'YES' WHEN NOT high_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN high_value THEN 'YES' WHEN NOT high_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN high_value THEN 'YES' WHEN NOT high_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN high_value THEN 'YES' WHEN NOT high_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN high_value THEN 'YES' WHEN NOT high_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN high_value THEN 'YES' WHEN NOT high_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN some_value THEN 'YES' WHEN NOT some_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN some_value THEN 'YES' WHEN NOT some_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN some_value THEN 'YES' WHEN NOT some_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN some_value THEN 'YES' WHEN NOT some_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN some_value THEN 'YES' WHEN NOT some_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN some_value THEN 'YES' WHEN NOT some_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN some_value THEN 'YES' WHEN NOT some_value THEN 'NO' ELSE 'MISSING' END ) AS group_col", 
			" ( CASE WHEN some_value THEN 'YES' WHEN NOT some_value THEN 'NO' ELSE 'MISSING' END ) AS group_col"
		)


	these_queries <-

		paste0(	
			
			"SELECT  " ,
			
				union_all_columns ,

				" , 
				
				AVG( numcol_one_numcol_two ) AS avg_one , 
				
				AVG( numcol_three ) AS avg_two , 
				
				AVG( numcol_four ) AS avg_three , 
				
				AVG( numcol_five ) AS avg_four
				
			FROM ( ( " ,
				
				paste0( "( SELECT 
				
						a.stringcol_one , a.stringcol_two ,
						
						( CASE WHEN some_value IS NULL THEN FALSE ELSE some_value END ) AS some_value ,
						
						( CASE WHEN high_value IS NULL THEN FALSE ELSE high_value END ) AS high_value ,
						
						( CASE WHEN numcol_one_numcol_two IS NULL THEN 0 ELSE numcol_one_numcol_two END ) AS numcol_one_numcol_two ,

						FALSE AS between_value ,
						
						( CASE WHEN numcol_three IS NULL THEN 0 ELSE numcol_three END ) AS numcol_three ,
						
						( CASE WHEN numcol_four IS NULL THEN 0 ELSE numcol_four END ) AS numcol_four ,
						
						( CASE WHEN numcol_five IS NULL THEN 0 ELSE numcol_five END ) AS numcol_five 
						
					FROM
						
						( SELECT stringcol_one , '" , 1:12 , "' AS stringcol_two FROM table_one ) AS a 
						
						LEFT JOIN 
						
						( 
							SELECT 
							
								stringcol_one , 
								
								CAST( MAX( ( numcol_two > 0 ) ) AS BOOLEAN ) AS some_value ,
								
								CAST( ( SUM( numcol_one + numcol_two ) >= 0 ) AS BOOLEAN ) AS high_value 
								
							FROM table_two 
								
							GROUP BY stringcol_one
						
						) AS z 

						ON a.stringcol_one = z.stringcol_one

						LEFT JOIN 
						
						( 
							SELECT 
							
								stringcol_one , stringcol_two ,
								
								SUM( numcol_one + numcol_two ) AS numcol_one_numcol_two ,
								
								SUM( numcol_three ) AS numcol_three , 
								
								SUM( numcol_four ) AS numcol_four , 
								
								SUM( numcol_five ) AS numcol_five 
								
							FROM table_two 
							
							GROUP BY stringcol_one , stringcol_two
						
						) AS b 
						
						ON a.stringcol_one = b.stringcol_one AND a.stringcol_two = b.stringcol_two )" , 
						
						collapse = ") UNION ALL (" ) ,
				
			") ) AS y GROUP BY group_col"

		)

		


	# this bug does NOT appear if you lower the number of unique
	# records in table_one from 500,000 to 400,000
	# in other words, if you set table_one_numrecs to 400000
	# instead of 500000, there's no error here
		
	# table_one_numrecs <- 400000
	table_one_numrecs <- 500000

	table_two_numrecs <- table_one_numrecs * 20

	# one column table of strings
	table_one <- data.frame( stringcol_one = digest::sha1( seq( table_one_numrecs ) ) , another_col = "hello" , stringsAsFactors = FALSE )

	# here's what the first six records of both tables look like.
	head( table_one )


	# this table includes random number generation.
	# set the seed so the random numbers are the same every time
	# for perfect reproducibility
	set.seed(1)

	table_two <- 
		data.frame( 
			stringcol_one = sample( table_one$stringcol_one , table_two_numrecs , replace = TRUE ) ,
			stringcol_two = sample( as.character( 1:12 ) , table_two_numrecs , replace = TRUE ) ,
			numcol_one = runif( table_one_numrecs , 0 , 1000000 ) / 100 ,
			numcol_two = runif( table_one_numrecs , 0 , 1000000 ) / 100 ,
			numcol_three = runif( table_one_numrecs , 0 , 1000000 ) / 100 ,
			numcol_four = runif( table_one_numrecs , 0 , 1000000 ) / 100 ,
			numcol_five = runif( table_one_numrecs , 0 , 1000000 ) / 100 , stringsAsFactors = FALSE
		)

	# here's what the first six records of table two looks like
	head( table_two )

	library(DBI)
	library(MonetDBLite)
	batfile <- 
		monetdb.server.setup( 
			file.path( tempdir() , "mserver" ) , 
			monetdb.program.path = 
							ifelse( 
								.Platform$OS.type == "windows" , 
								"C:/Program Files/MonetDB/MonetDB5" , 
								"" 
							) 
		)

	pid <- monetdb.server.start(batfile)
	db_mserver <- dbConnect( MonetDBLite::MonetDB.R() , wait = TRUE )
	db_lite <- dbConnect( MonetDBLite::MonetDBLite() , file.path( tempdir() , "mserver" ) )


	# add both tables to the database
	tf1 <- tempfile()
	write.csv( table_one , tf1 , row.names = FALSE )

	tf2 <- tempfile()
	write.csv( table_two , tf2 , row.names = FALSE )


	dbWriteTable( db_mserver , 'table_one' , tf1 )
	dbWriteTable( db_mserver , 'table_two' , tf2 )

	dbWriteTable( db_lite , 'table_one' , tf1 )
	dbWriteTable( db_lite , 'table_two' , tf2 )



	# here's the full stacked query
	this_query <- paste( "( (" , paste( these_queries , collapse = ") UNION ALL (" ) , ") )" )
		
	# works
	this_level <- dbGetQuery( db_mserver , this_query )
	# fails
	this_level <- dbGetQuery( db_lite , this_query )

	# write explain and plan to home directory
	lite_query_explain <- dbGetQuery( db_lite , paste( "EXPLAIN" , this_query ) )
	writeLines( lite_query_explain[ , 1 ] , file.path( path.expand( "~" ) , "lite_query_explain.txt" ) )
	lite_query_plan <- dbGetQuery( db_lite , paste( "PLAN" , this_query ) )
	writeLines( lite_query_plan[ , 1 ] , file.path( path.expand( "~" ) , "lite_query_plan.txt" ) )

**Comment by ajdamico** [comment]
https://github.com/hannesmuehleisen/MonetDBLite/commit/f1b1cbe712a4d3f3bdefd8489a1df29d4bd7e16a appears to have solved this minimal reproducible example.  i'll check whether it's also solved in some larger `UNION ALL` queries i have.  thanks so much @hannesmuehleisen and @Mytherin

**Comment by hannesmuehleisen** [comment]
ahahahahaha excellent

**Comment by ajdamico** [comment]
haha gonna open a separate github issue for your evil laugh spelling

**Comment by ajdamico** [comment]
as far as i can tell, this is out of our lives in jul2017lite-r branch.  thank you again for fixing
