### ISSUE TITLE
Publishing shiny app creates error trying to read database

### ISSUE THREAD

**Issue by aakbarie** [hannesmuehleisen/MonetDBLite#128]
I have created a shiny app that loads data from a MonetDB database. The shiny app works just fine inside RStudio, but when I publish it to my shiny server, I get the following error:
```
cannot create dir '/...', reason 'Permission denied'

Warning: Error in monetdb_embedded_startup: Cannot create /.../DB
```

I know that DB does exists and ... is same location. And my Shiny server does have access to that DB because I can run R and access it on the server.
Any suggestions would be welcomed. What I am really struggling with is to understand the `'cannot create dir'` error, since I am not asking for new directory and I am just creating a connecting to the DB
```
dbdir <- ".../DB"
 
 con <- dbConnect(MonetDBLite::MonetDBLite(), dbdir)
```

**Comment by hannesmuehleisen** [comment]
See #71, also, could you provide a fully reproducible example perhaps?

**Comment by hannesmuehleisen** [comment]
closing as duplicate
