### ISSUE TITLE
In-memory mode

### ISSUE THREAD

**Issue by mrecht** [hannesmuehleisen/MonetDBLite#129]
In my opinion it would be very valuable to have an in-memory mode - without a disk backed database.
It would help in cases of ad-hoc analytics. For now I sort of simulate this with creating a temporary directory and then deleting it, but this comes with a certain overhead.

**Comment by hannesmuehleisen** [comment]
On recent Linux distros, you could use `/dev/shm/something` as a DB folder.

**Comment by mrecht** [comment]
Indeed! Thanks for the tip! Is there a similar mechanism for Windows as well?

**Comment by hannesmuehleisen** [comment]
Not that I know of. If there was something like `/dev/shm` on OSX and Windows as well, I would consider adding some support for it. But for now I hope the workaround is ok.

**Comment by hannesmuehleisen** [comment]
We are looking into this at the moment, results are promising.

**Comment by hannesmuehleisen** [comment]
The C version of MonetDBLite has an in-memory mode now, will port this to the R version asap.

**Comment by hannesmuehleisen** [comment]
R and Python frontends now support :memory: as DB directory (same as SQLite)
