### ISSUE TITLE
dbWriteTable fails on MonetDBConnection objects

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#130]
any idea if i'm doing something dumb?  thanks

using today's install:

	# devtools::install_github( "hannesmuehleisen/MonetDBLite" )
	
	library(DBI)
	library(MonetDBLite)

	dbdir <- tempdir()

	batfile <- 
		monetdb.server.setup( 
			dbdir , 
			monetdb.program.path = "C:/Program Files/MonetDB/MonetDB5" , 
			dbname = "demo" , 
			dbport = 50000 
		)

	pid <- monetdb.server.start( batfile )

	db <- dbConnect( MonetDBLite::MonetDB.R() , "monetdb://localhost:50000/demo" , wait = TRUE )

	dbWriteTable( db , 'mtcars' , mtcars )

gives

	Error in .Call("mapi_split", res@env$data[1:n], as.integer(info$cols),  : 
	  "mapi_split" not available for .Call() for package "libmonetdb5"

sessionInfo()

	R version 3.3.3 (2017-03-06)
	Platform: x86_64-w64-mingw32/x64 (64-bit)
	Running under: Windows Server 2012 R2 x64 (build 9600)

	locale:
	[1] LC_COLLATE=English_United States.1252 
	[2] LC_CTYPE=English_United States.1252   
	[3] LC_MONETARY=English_United States.1252
	[4] LC_NUMERIC=C                          
	[5] LC_TIME=English_United States.1252    

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base     

	other attached packages:
	[1] MonetDBLite_0.3.2 DBI_0.6-1        

	loaded via a namespace (and not attached):
	[1] codetools_0.2-15 digest_0.6.12

**Comment by hannesmuehleisen** [comment]
err thats odd...  that seems to indicate the symbol is not there or not exported. Will check.

**Comment by hannesmuehleisen** [comment]
What happens on Linux?

**Comment by ajdamico** [comment]
windows-only bug.  using today's dev monetdblite, this code works:

	library(DBI)
	library(MonetDBLite)

	dbdir <- tempdir()

	batfile <- monetdb.server.setup( dbdir , monetdb.program.path = "/export/scratch1/home/damico/MonetDB/bin" )

	pid <- monetdb.server.start( batfile )

	db <- dbConnect( MonetDBLite::MonetDB.R() , "monetdb://localhost:50000/demo" , wait = TRUE )

	dbWriteTable( db , 'mtcars' , mtcars )

**Comment by hannesmuehleisen** [comment]
confirmed here on Windows 10

**Comment by ajdamico** [comment]
this still fails for factor columns..  probably should be fixed in master branch not `Jul2017Lite-R`  thanks


	# fails
	table_one <- data.frame( character_col = "hello" )
	dbWriteTable( db , 'table_one' , table_one )

	# works
	table_one$character_col <- as.character( table_one$character_col )
	dbWriteTable( db , 'table_one' , table_one )



column of factors failure detail

	> table_one <- data.frame( character_col = "hello" )
	> 
	> dbWriteTable( db , 'table_one' , table_one )
	Error in .local(conn, statement, ...) : 
	  Unable to execute statement 'INSERT INTO table_one VALUES (hello)'.
	Server says '!SELECT: identifier 'hello' unknown'.
	> traceback()
	13: stop("Unable to execute statement '", statement, "'.\nServer says '", 
			env$message, "'.")
	12: .local(conn, statement, ...)
	11: dbSendQuery(conn, statement, ...)
	10: dbSendQuery(conn, statement, ...)
	9: dbSendStatement(conn, statement, ...)
	8: dbSendStatement(conn, statement, ...)
	7: dbExecute(conn, paste0("INSERT INTO ", qname, " VALUES ", paste0(bvins, 
		   collapse = ", ")))
	6: dbExecute(conn, paste0("INSERT INTO ", qname, " VALUES ", paste0(bvins, 
		   collapse = ", ")))
	5: FUN(X[[i]], ...)
	4: lapply(split(value, splitlen), function(valueck) {
		   bvins <- c()
		   for (j in 1:length(valueck[[1]])) bvins <- c(bvins, .bindParameters(vins, 
			   as.list(valueck[j, ])))
		   dbExecute(conn, paste0("INSERT INTO ", qname, " VALUES ", 
			   paste0(bvins, collapse = ", ")))
	   })
	3: .local(conn, name, value, ...)
	2: dbWriteTable(db, "table_one", table_one)
	1: dbWriteTable(db, "table_one", table_one)
	> table_one
	  character_col
	1         hello
	> 
	> 

works

	> table_one$character_col <- as.character( table_one$character_col )
	> dbWriteTable( db , 'table_one' , table_one )
	>

**Comment by hannesmuehleisen** [comment]
This is a completely separate issue but yes, will be fixed.
