### ISSUE TITLE
CORR division by zero error different behavior from mserver

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#132]
not sure if a fix to https://www.monetdb.org/bugzilla/show_bug.cgi?id=6287 will resolve this issue

	library(DBI)
	db <- dbConnect( MonetDBLite::MonetDBLite() )

	dbSendQuery( db , "CREATE TABLE x ( a DOUBLE , b INTEGER )")
	dbSendQuery( db , "INSERT INTO x VALUES (0.1,0)")
	dbSendQuery( db , "INSERT INTO x VALUES (0.9,1)")
	dbGetQuery( db , "SELECT CORR( a , b ) FROM x")

	dbSendQuery( db , "CREATE TABLE y ( a INTEGER , b DOUBLE )")
	dbSendQuery( db , "INSERT INTO y VALUES (0,0.1)")
	dbSendQuery( db , "INSERT INTO y VALUES (1,0.9)")
	dbGetQuery( db , "SELECT CORR( a , b ) FROM y")
	# Error in .local(conn, statement, ...) : 
	  # Unable to execute statement 'SELECT CORR( a , b ) FROM y'.
	# Server says 'MALException:calc./:22012!division by zero.

comparable mserver code.  the last line (incorrectly) returns an integer.

	CREATE TABLE x ( a DOUBLE , b INTEGER );
	INSERT INTO x VALUES (0.1,0);
	INSERT INTO x VALUES (0.9,1);
	SELECT CORR( a , b ) FROM x;

	CREATE TABLE y ( a INTEGER , b DOUBLE );
	INSERT INTO y VALUES (0,0.1);
	INSERT INTO y VALUES (1,0.9);
	SELECT CORR( a , b ) FROM y;

**Comment by hannesmuehleisen** [comment]
which mserver is this?

**Comment by ajdamico** [comment]
latest.  definitely not worth your time until 6287 gets a look

**Comment by hannesmuehleisen** [comment]
if we are doing it correctly, then its a monetdb bug no?

**Comment by ajdamico** [comment]
two things are happening: 1) monetdb is doing something wrong. 2) monetdblite is doing something differently from monetdb. i don't think it's worth looking into 2 until 1 gets resolved

**Comment by hannes** [comment]
Its now consistent and works
