### ISSUE TITLE
dplyr 0.5 compatibility

### ISSUE THREAD

**Issue by hannesmuehleisen** [hannesmuehleisen/MonetDBLite#138]
different from the 0.6 compatibility we have now :(

**Comment by ajdamico** [comment]
why not simply `dplyr (>= 0.6.0)`  in `Suggests:` ?  did the release candidate get delayed?

**Comment by hannesmuehleisen** [comment]
0.5 is on cran and the only one which matters for CRAN check

**Comment by ajdamico** [comment]
airplane holding pattern github issue.  got it.

**Comment by hannesmuehleisen** [comment]
dplyr 0.6 and dbplyr will be submitted to cran on May 11, so indeed I will not add dplyr 0.5 compat but rather wait. Adding explicit version numbers to DESCRIPTION and close.
