### ISSUE TITLE
add a more helpful error message if `dbdir` gets used on a MonetDBLite `conn=` parameters

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#139]
took me a while to see that this error is correct

	> dbdir <- "D:/DADOS_DOUT/teste_monet/"
	> mdb <- dbConnect( MonetDBLite::MonetDBLite(), dbdir)
	> monetdb.read.csv(conn = dbdir, 
	+                  files = 'D:/DADOS_DOUT/INEP/CES/2015/CURSO_2.csv', 
	+                  tablename = 'curso_2015', 
	+                  header = TRUE, 
	+                  na.strings = '', 
	+                  delim = '|')
	Error in (function (classes, fdef, mtable)  : 
	  unable to find an inherited method for function ‘dbBegin’ for signature ‘"character"’

**Comment by hannesmuehleisen** [comment]
nothing i can do there its a DBI thing

**Comment by ajdamico** [comment]
there is room between the `MonetDBLite::monetdb.read.csv` call and the `DBI::dbBegin` call to check for this user mistake.  do you think that's misplaced, though?

**Comment by ajdamico** [comment]
@hannesmuehleisen i think you're right this isn't worth changing in `MonetDBLite`.  i'm not expert enough to figure out a succinct pull request to improve the error message in `DBI` either.  pinging @krlmlr just in case there's some easy way to improve the error message for this user mistake but probably not worth it.  thanks


	library(DBI)
	database_directory <- tempdir()
	my_connection <- dbConnect( MonetDBLite::MonetDBLite() , database_directory )
	dbWriteTable( database_directory , 'mtcars' , mtcars )
	# Error in (function (classes, fdef, mtable)  : 
	  # unable to find an inherited method for function ‘dbWriteTable’ for signature ‘"character", "character"’

**Comment by krlmlr** [comment]
This is an error message from failed S4 dispatch, nothing DBI can do here. I'm forgetting to pass `conn` and `res` arguments all the time when using DBI, I'm thinking a lightweight R6 wrapper around DBI could give a better experience.

**Comment by ajdamico** [comment]
thanks for your time
