### ISSUE TITLE
dplyr::copy_to() failure

### ISSUE THREAD

**Issue by nalimilan** [hannesmuehleisen/MonetDBLite#140]
I always get an error when trying to use dplyr's `copy_to` function. Is this expected? I'm using latest git master.

```R
> library(dplyr)
> db <- MonetDBLite::src_monetdblite("tmp", create=TRUE)
> copy_to(db, iris)
Identifier(s) "'iris'" contain uppercase or reserved SQL characters and need(s) to be quoted in queries.
Identifier(s) "Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species" contain uppercase or reserved SQL characters and need(s) to be quoted in queries.
Error in .local(conn, statement, ...) : 
  Unable to execute statement 'select count(*) as is_tmp_schema from sys.tables join sys.schemas on tables.schema_id=schemas.id whe...'.
Server says 'syntax error, unexpected IDENT, expecting SCOLON in: "select count(*) as is_tmp_schema from sys.tables join sys.schemas on tables.sche" ' [#42000].
```

**Comment by ajdamico** [comment]
hi, i can't even get this working on windows?

	devtools::install_github("tidyverse/rlang",dependencies=TRUE)
	devtools::install_github("hadley/dbplyr",dependencies=TRUE)
	devtools::install_github("tidyverse/tidyverse",dependencies=TRUE)

we might want to wait till dplyr `0.6.0` goes to cran?

**Comment by hannesmuehleisen** [comment]
I have a pr on dbplyr that fixes this

**Comment by hannesmuehleisen** [comment]
Try installing `devtools::install_github("hannesmuehleisen/dbplyr")` for now

**Comment by nalimilan** [comment]
Thanks, it works. Unfortunately, I have other issues when using dplyr with dbplyr master, so I think I'll have to wait until it stabilizes.

**Comment by hannesmuehleisen** [comment]
dblyr fix was merged, so closing here
