### ISSUE TITLE
union all bug check

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#141]
devtools::install_github("hannesmuehleisen/MonetDBLite", ref="Jul2017Lite-R")

**Comment by ajdamico** [comment]
running the code at https://www.monetdb.org/bugzilla/show_bug.cgi?id=6211 still gives an error.  closing this and writing a note there



	Error in .local(conn, statement, ...) : 
	  Unable to execute statement '( ( SELECT  NULL AS group_col , 

	AVG( numcol_one_numcol_two ) AS avg_one , 

	AVG( numcol_three ) AS...'.
	Server says 'MALException:opt.remap:Function 'calc.>' not defined'.



	> sessionInfo()
	R version 3.4.0 (2017-04-21)
	Platform: x86_64-w64-mingw32/x64 (64-bit)
	Running under: Windows 10 x64 (build 14393)

	Matrix products: default

	locale:
	[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
	[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
	[5] LC_TIME=English_United States.1252    

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base     

	other attached packages:
	[1] DBI_0.6-1

	loaded via a namespace (and not attached):
	[1] compiler_3.4.0    MonetDBLite_0.3.3 codetools_0.2-15  digest_0.6.12    
	>

**Comment by hannesmuehleisen** [comment]
woop its not my fault

**Comment by ajdamico** [comment]
that is an open question.  i asked for the best way to check in the
bugzilla thread:  how do i install a windows mserver at the exact same
timepoint?  thanks
