### ISSUE TITLE
db empty after connection closed and create again

### ISSUE THREAD

**Issue by gushenghua** [hannesmuehleisen/MonetDBLite#142]
code:

g_path = os.path.expanduser("~/.alpha_quant_db")
conn = alpha_dbutility.create_db_connection(db='chinese_stock_history2016')
cursor = conn.cursor()

start2 = time.time()
sql = "SELECT * FROM chinese_stock_history2016"
cursor.execute(sql)
result = cursor.fetchall()# read data from a sqlite3 table
end2 = time.time()

print "time2 ", end2-start2

conn = monetdblite.connect(g_path+'/chinese_stock_history2016.mdb')

cur = conn.cursor()
try:
    sql = "CREATE TABLE " + "chinese_stock_history2016" + " (stockid VARCHAR(6), date VARCHAR(10), open REAL, high REAL, low REAL, close REAL, volume BIGINT, adjclose REAL, PRIMARY KEY (stockid, date))"
    cur.execute(sql)

except:
    pass

cursor.executemany('replace into chinese_stock_history2016 VALUES (?,?,?,?,?,?,?,?)', result)

sql = "SELECT count(*) FROM chinese_stock_history2016"
cursor.execute(sql)
result = cursor.fetchall()

conn.commit()
conn.close()

conn = monetdblite.connect(g_path+'/chinese_stock_history2016.mdb')
cursor = conn.cursor()

sql = "SELECT count(*) FROM chinese_stock_history2016"
cursor.execute(sql)
result = cursor.fetchall()
print result  #count equals 0

**Comment by hannesmuehleisen** [comment]
Could you please make this a reproducible example? We don't have the code for `alpha_dbutility` nor the `chinese_stock_history2016` data

**Comment by gushenghua** [comment]
I am sorry, I found a bug.
