### ISSUE TITLE
please upload latest eanthony onto both sisyphus machines

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#143]
your decision if you want to wait till cran upload.  this upload will break most everything but i will be able to gradually fix things on my own.  thanks

**Comment by ajdamico** [comment]
thanks so much

**Comment by ajdamico** [comment]
sorry for the hassle, please upload the latest version of the eanthony repo to both machines

i needed to fix another file.path(path.expand( mistake i had made previously.  i've tested on both rocks010 and rocks109 and things now should work properly..  thanks

https://github.com/ajdamico/asdfreebook/commit/cde111b6ef1f7aba26875e60947ec3e5de57ea3e
https://github.com/MonetDB/eanthony/commit/69e8316d7a2b0e985ffbb1b570adcf29999b0ff3

**Comment by hannesmuehleisen** [comment]
reloaded linux, but windows (damn it) crashed the git pull because some files were still in use. trying again tomorrow.

**Comment by ajdamico** [comment]
thanks a lot
