### ISSUE TITLE
python process got lock denied error while another process is inserting data

### ISSUE THREAD

**Issue by gushenghua** [hannesmuehleisen/MonetDBLite#146]
monetdblite.exceptions.DatabaseError: Failed to initialize MonetDB: !FATAL: GDKl
ockHome: Database lock '.gdk_lock' denied

**Comment by ajdamico** [comment]
hello, this happens when a different process is still holding the database.  try restarting your computer and confirm that only the one instance is accessing the database at a time?  for more detail, see https://github.com/hannesmuehleisen/MonetDBLite/blob/master/README.md#shutdown  thanks

**Comment by gushenghua** [comment]
so it means only one process can access the database at one moment?

**Comment by ajdamico** [comment]
hi, for the R version, only one *session* can access the database at a time.  i am not sure how the restriction applies for the java/python version? cc @pedrotadim  thanks

**Comment by hannesmuehleisen** [comment]
same for other versions, and yes, only once process can access the db at one point. if you want a different behavior, you can install a monetdb server or roll your own rpc thing
