### ISSUE TITLE
multi thread problem

### ISSUE THREAD

**Issue by gushenghua** [hannesmuehleisen/MonetDBLite#148]
Is it safe to share one database connection among multi python thread?  Some strange errors happended when I did it.

 (<class 'monetdblite.exceptions.DatabaseError'>, DatabaseError('SQLException:mvc:SQL module not initialized',), <traceback object at 0x0000000003C98E08>)

**Comment by gushenghua** [comment]
Does connection will be closed by monetdb after a lot of "PRIMARY KEY constraint violated errors"?

(<class 'monetdblite.exceptions.DatabaseError'>, DatabaseError('SQL Query Failed: Invalid connection',), <traceback object at 0x0000000004391348>)

**Comment by hannesmuehleisen** [comment]
No, should not happen. Can you give a reproducible example please?

**Comment by hannesmuehleisen** [comment]
And no, you should not share a connection between threads.
