### ISSUE TITLE
DATE, TIME, DATETIME, DECIMAL, BOOLEAN proper support in MonetDBLite

### ISSUE THREAD

**Issue by hannesmuehleisen** [hannesmuehleisen/MonetDBLite#15]
We are not converting these properly currently in either direction.

``` R
library(DBI)
library(MonetDB.R)
library(MonetDBLite)

db <- dbConnect( MonetDBLite() )
x <- mtcars

# this causes the problem
x$hello <- Sys.Date() - seq( nrow( x ) )

dbWriteTable( db , 'x' , x )
x <- x[ , sort( names( x ) ) ]
dbWriteTable( db , 'x' , x , append = TRUE )
```

**Comment by hannesmuehleisen** [comment]
Also BOOLEANs don't have the proper R type here

**Comment by hannesmuehleisen** [comment]
decimals and booleans are supported now in Jul2017 branch

**Comment by hannesmuehleisen** [comment]
So, what should we do with TIME? there is no native R type for this... @ajdamico  any idea?

**Comment by ajdamico** [comment]
no ideas..  sqlite does not have a TIME type either, so i don't think you have behavior you can copy here.  what are your options aside from coercing to DATETIME?

**Comment by hannesmuehleisen** [comment]
could convert to string

**Comment by hannesmuehleisen** [comment]
or use POSIXct with pointless year
 as.POSIXct("0000-01-01 12:12")

**Comment by ajdamico** [comment]
no strong feelings from me.  whatever you decide, a coercion warning would be good..

**Comment by hannesmuehleisen** [comment]
opened issue in DBI https://github.com/rstats-db/DBI/issues/182

**Comment by hannesmuehleisen** [comment]
use difftime

**Comment by hannesmuehleisen** [comment]
See https://github.com/hannesmuehleisen/MonetDBLite/commit/c4e1a5096d7f209e164abad05cde20d93817f5f6
