### ISSUE TITLE
Error: 'src_sql' is not an exported object from 'namespace:dplyr'

### ISSUE THREAD

**Issue by lptolik** [hannesmuehleisen/MonetDBLite#167]
Hi,

I've recently updated version of the dplyr package and got the following error: 

> library(DBI)
library(dplyr)
library(MonetDBLite)
dbdir <- '~/path/to/db/dir/'
prepareCon<-function(dbdir){
  con <- dbConnect(MonetDBLite::MonetDBLite(), dbdir)
  if(dbIsValid(con)){
    cat(paste(dbGetInfo(con),collapse = '\n'))
  }else{
    stop('DB is not connected')
  }
  dbBegin(con)
  return(con)
}
con <- prepareCon(dbdir)
monetdb_conn <- src_monetdb(con = con)

The last statement returns an error:

> Error: 'src_sql' is not an exported object from 'namespace:dplyr'

The connection is working fine, the problem is in dplyr association.

Recent dplyr documentation proposed to call dplyr::tbl with connection:

>t<- tbl(con,'spectra')
Error in dbFetch(qry, 0) : Fetch 0 rows? Really?

That does not work as well. 
The code was functional with dplyr 0.5, on their site they listed that type of errors and send to your bugtracker.

**Comment by ajdamico** [comment]
hi, could you double-check this with the development version?  i cannot reproduce these errors

    devtools::install_github("hannesmuehleisen/MonetDBLite")

**Comment by lptolik** [comment]
> devtools::install_github("hannesmuehleisen/MonetDBLite")
Downloading GitHub repo hannesmuehleisen/MonetDBLite@master
from URL https://api.github.com/repos/hannesmuehleisen/MonetDBLite/zipball/master
Installation failed: Could not find build tools necessary to build MonetDBLite

CRAN version installed properly.

**Comment by ajdamico** [comment]
hi, that sounds like a separate issue.  please do some googling to fix.  maybe this?  thanks

https://github.com/hadley/devtools/issues/1176#issuecomment-217750428

**Comment by lptolik** [comment]
Hi, I'm on MacOS:

R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MonetDBLite_0.3.1

loaded via a namespace (and not attached):
 [1] httr_1.2.1       R6_2.2.2         DBI_0.7          tools_3.3.2      withr_1.0.2      curl_2.7         memoise_1.1.0    codetools_0.2-15
 [9] git2r_0.18.0     digest_0.6.12    devtools_1.13.2

**Comment by ajdamico** [comment]
i do not think your issue is related to monetdblite?  did you upgrade gcc?

**Comment by hannesmuehleisen** [comment]
I think you need to install Xcode command line tools

**Comment by lptolik** [comment]
yes, I've updated clang, gcc, installed R 3.4 and now I have a problem with shared library:

> devtools::install_github("hannesmuehleisen/MonetDBLite")
Downloading GitHub repo hannesmuehleisen/MonetDBLite@master
from URL https://api.github.com/repos/hannesmuehleisen/MonetDBLite/zipball/master
Installing MonetDBLite
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/b2/vx2cstxj6kd4_0tc428h4_qm0000gn/T/RtmpCcWTc9/devtools7c852406336e/hannesmuehleisen-MonetDBLite-3cb70b3'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘MonetDBLite’ ...
configure: creating cache config.cache
checking build system type... x86_64-apple-darwin16.6.0
checking host system type... x86_64-apple-darwin16.6.0
checking target system type... x86_64-apple-darwin16.6.0
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for style of include used by make... GNU
checking for gcc... /usr/local/opt/llvm/bin/clang -fopenmp
checking whether the C compiler works... no
configure: error: in `/private/var/folders/b2/vx2cstxj6kd4_0tc428h4_qm0000gn/T/RtmpCcWTc9/devtools7c852406336e/hannesmuehleisen-MonetDBLite-3cb70b3/src':
configure: error: C compiler cannot create executables
See `config.log' for more details
rm: libmonetdb5.so: No such file or directory
** libs
** arch - 
/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB -lz -o libmonetdb5.so `find  -name "*.o" | xargs echo` 
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘MonetDBLite’ in library.dynam(lib, package, package.lib):
 shared object ‘libmonetdb5.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/MonetDBLite’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/MonetDBLite’
Installation failed: Command failed (1)

I have reinstall monetdb via Homebrew, but I don't have libmonetdb5.so, I have libmonetdb5.dylib

**Comment by hannesmuehleisen** [comment]
" C compiler cannot create executables " that's the issue here I think.

**Comment by lptolik** [comment]
Hi,
I've manage to compile, the problem was in OpenMP support in clang4 for Mac. 
The error disappeared with version from github, but a can confirm, that the error exists on CRAN binary version for Mac and Windows.

Cheers,
Anatoly

**Comment by ajdamico** [comment]
makes sense since there was a big dplyr update recently and the monetdblite cran version is a year old.  i think hannes plans to release the github version to cran in the next month.  thanks for following up!
