### ISSUE TITLE
round-trip for time, datetime, timestamps

### ISSUE THREAD

**Issue by hannesmuehleisen** [hannesmuehleisen/MonetDBLite#168]
reading those works, but writing from r not yet

**Comment by mclements** [comment]
Writing Dates from R may also not work (int vs double). The following patch worked for me. Apologies for not providing a proper pull request. Sincerely, Mark.

diff --git a/src/embedded/converters.c.h b/src/embedded/converters.c.h
index bddcee9..2502761 100644
--- a/src/embedded/converters.c.h
+++ b/src/embedded/converters.c.h
@@ -544,6 +544,13 @@ static BAT* sexp_to_bat(SEXP s, int type) {
                SXP_TO_BAT(int, NUMERIC_POINTER, ISNA(*p));
                b = BATcalcaddcst(b, &val, NULL, TYPE_int, 1);
        }
+       if (type == TYPE_date && IS_INTEGER(s) && strcmp("Date", CHAR(STRING_ELT(GET_CLASS(s), 0))) == 0) {
+               ValRecord val;
+               val.vtype = TYPE_int;
+               val.val.ival = 719528;
+               SXP_TO_BAT(int, INTEGER_POINTER, *p==NA_INTEGER);
+               b = BATcalcaddcst(b, &val, NULL, TYPE_int, 1);
+       }
 
        if (type == TYPE_timestamp && IS_NUMERIC(s) && strcmp("POSIXct", CHAR(STRING_ELT(GET_CLASS(s), 0))) == 0) {
                size_t j; timestamp *p, epoch;

**Comment by mclements** [comment]
Writing Dates from R to MonetDBLite also did not work for me (int vs double). The attached patch seemed to help. Apologies for not providing a full pull request: the GitHub repository is huge. Sincerely, Mark.

[write_Date.txt](https://github.com/hannesmuehleisen/MonetDBLite/files/1151387/write_Date.txt)

**Comment by hannesmuehleisen** [comment]
@mclements, thanks, will add your changes! Also, a shallow clone (`git clone --depth=10`) might have helped to speed up cloning.

**Comment by mclements** [comment]
@hannesmuehleisen, unfortunately and surprisingly, `IS_NUMERIC(s)` is false when `IS_INTEGER(s)` is true. My original patch may still be required.

Thank you for suggesting the shallow clone -- much better!

**Comment by hannesmuehleisen** [comment]
err can you please give a minimal example for me to add to a test case?

**Comment by mclements** [comment]
I have now (i) produced a pull request and (ii) provided a minimal example in a comment to the pull request. This bug only surfaced from using `foreign::read.dta()`.

On 07/18/2017 12:55 PM, Hannes Mühleisen wrote:

err can you please give a minimal example for me to add to a test case?

**Comment by hannesmuehleisen** [comment]
thanks, merged your PR and added a test case based on your code https://github.com/hannesmuehleisen/MonetDBLite/blob/master/tests/testthat/test_02_dbi.R#L385
