### ISSUE TITLE
Make prepared statements work (great again)

### ISSUE THREAD

**Issue by hannesmuehleisen** [hannesmuehleisen/MonetDBLite#170]
at least manually

CC @PedroTadim

**Comment by hannesmuehleisen** [comment]
@Mytherin maybe also interesting for you to add prepared statement support to python version

**Comment by PedroTadim** [comment]
To start the mvc_export_prepare must be changed: https://github.com/hannesmuehleisen/MonetDBLite/blob/Jul2017Lite-Java/src/sql/backends/monet5/sql_result.c#L980

**Comment by Mytherin** [comment]
Sure, right now the Python equivalent of prepared statements are implemented on the Python level using string replacements. They could be changed to use MonetDB's prepared statements instead.

**Comment by hannesmuehleisen** [comment]
@PedroTadim if you look at the master branch you will see that mvc_export_prepare has been rewritten.
