### ISSUE TITLE
Fix crash bsapuf

### ISSUE THREAD

**Issue by hannesmuehleisen** [hannesmuehleisen/MonetDBLite#177]

**Comment by ajdamico** [comment]
thanks

https://sisyphus.project.cwi.nl/stones06fedora/1500488359/acs.log
https://sisyphus.project.cwi.nl/stones06fedora/1500522996/pnad.log
https://sisyphus.project.cwi.nl/stones06fedora/1500522996/bsapuf.log

**Comment by hannesmuehleisen** [comment]
Could not reproduce either of those in isolation
