### ISSUE TITLE
Allow debugging commands like EXPLAIN 

### ISSUE THREAD

**Issue by hannesmuehleisen** [hannesmuehleisen/MonetDBLite#18]
``` R
library(DBI)
db <- dbConnect( MonetDB.R::MonetDBLite() )
dbSendQuery( db , "CREATE TABLE test AS SELECT 1 AS one WITH DATA" )
dbGetQuery( db , "EXPLAIN SELECT * FROM TEST" )
```

**Comment by hannesmuehleisen** [comment]
also support `dplyr::db_explain`

**Comment by hannesmuehleisen** [comment]
`dbGetQuery(con, "PLAN SELECT ...")` now gives the relational plan, also support added for `dplyr::explain()`

**Comment by lea-urpa** [comment]
Do you also have support for EXPLAIN in connections with MonetDBLite, not just MonetDB.R ?

**Comment by ajdamico** [comment]
hi, this should be available with the development version?  soon to be on cran but you can use it now with

    devtools::install_github("hannesmuehleisen/MonetDBLite")

**Comment by lea-urpa** [comment]
Great, it works like a charm. Any chance TRACE is also available in MonetDBLite?

**Comment by hannesmuehleisen** [comment]
No, due to the unique way trace is implemented this is not yet supported. We may add equivalent functionality at some point.
