### ISSUE TITLE
dbWriteTable() method information loss warning

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#22]
inside MonetDB.R 1.0.2's dbi.R  `dbWriteTable` method, directly after the line

```
if (length(value) < 1) stop("value must have at least one column")
```

could you add this single line, or something like it?  or is it too much computation?

```
if(any(is.infinite(unlist(value)))|any(is.nan(unlist(value)))) warning("special R types -Inf, Inf, and NaN coerce to NULL in MonetDBLite tables")
```

thanks

**Comment by hannesmuehleisen** [comment]
Need to get numbers on how long that would take

**Comment by ajdamico** [comment]
i'll try this

**Comment by ajdamico** [comment]
yup.  nope.

	> system.time(value <- mtcars[ rep( seq(nrow(mtcars)),100000),])
	   user  system elapsed 
	   6.98    0.18    7.16 
	> system.time(any(is.infinite(unlist(value)))|any(is.nan(unlist(value))))
	   user  system elapsed 
	  72.54    1.03   73.71
