### ISSUE TITLE
consolidate MonetDB.R code into MonetDBLite

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#23]

**Comment by hannesmuehleisen** [comment]
uuuh testing this right now

**Comment by hannesmuehleisen** [comment]
this will require to remove all library(MonetDB.R) calls from scripts at some point are you ready for this?

**Comment by hannesmuehleisen** [comment]
also, 	

`db <- dbConnect( MonetDBLite::MonetDBLite() , dbfolder )`

is the way to go then

**Comment by hannesmuehleisen** [comment]
https://github.com/hannesmuehleisen/MonetDBLite/commit/54a90eaad08b977e1041e01664a1a70cc43003d7
