### ISSUE TITLE
rename MonetDB.R driver to work with sqldf

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#24]
"Currently any driver name prefaced with R or r is accepted by sqldf and that rule should not be changed"

source: https://github.com/ggrothendieck/sqldf/pull/4#issuecomment-158962160

**Comment by hannesmuehleisen** [comment]
added alias, RMonetDB

**Comment by hannesmuehleisen** [comment]
There is a MonetDBLite::RMonetDBLite driver constructor function now
