### ISSUE TITLE
dbDriver("MonetDBLite") needs library(MonetDBLite)

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#25]
library(DBI)
    m <- dbDriver("MonetDBLite")

> Error: Couldn't find driver MonetDBLite. Looked in:
> * global namespace
> * in package called MonetDBLite
> * in package called RMonetDBLite

    library(MonetDBLite)
    m <- dbDriver("MonetDBLite")
    # works

**Comment by hannesmuehleisen** [comment]
Need to figure out what on earth dbDriver does here

**Comment by ajdamico** [comment]
yeowch

**Comment by hannesmuehleisen** [comment]
This works as intended. You need to call `library(MonetDBLite)` or `loadNamespace("MonetDBLite")` before `dbDriver()`. Essentially, it checks if   `"MonetDBLite" %in% loadedNamespaces()`.

**Comment by ajdamico** [comment]
thanks
