### ISSUE TITLE
fix syntax on main monetdblite blog post

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#36]
currently refers to monetdb.r  https://www.monetdb.org/blog/monetdblite-r

**Comment by hannesmuehleisen** [comment]
need to wait with cran submit before we can update

**Comment by ajdamico** [comment]
@HanOostdijk blog post being incorrect is reported here   ;)

**Comment by ajdamico** [comment]
@hannesmuehleisen until you fix #59 it might be good to update the blog post just so others aren't thrown off?

**Comment by hannesmuehleisen** [comment]
yes. we should update or refer to the github readme

**Comment by ajdamico** [comment]
at least the couple of lines that reveal the bug..

	library(DBI)
	dbdir <- tempdir()
	con <- dbConnect(MonetDB.R::MonetDB(), embedded = dbdir)
	dbWriteTable(con, "mtcars", mtcars)
	dbGetQuery(con, "SELECT MAX(mpg) FROM mtcars WHERE cyl = 8")

**Comment by ajdamico** [comment]
if you accept this pull request, `src_monetdb` in the blog post should also change to `src_monetdblite`

https://github.com/hannesmuehleisen/MonetDBLite/pull/66

**Comment by cronacronis** [comment]
It is very confusing, becasuse it is hard to find **working** documentation. Would you mind to share working piece of code for CRAN version to make insert to a MonetDBLite located in the custom folder with `dbConnect` and get with `dplyr src_`?

**Comment by ajdamico** [comment]
https://github.com/hannesmuehleisen/MonetDBLite/blob/master/tests/testthat/test_03_dplyr.R

**Comment by hannesmuehleisen** [comment]
updated blog post sorry for confusion
