### ISSUE TITLE
dplyr copy_to bug

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#37]
one of these two things should not happen, right?

	library(MonetDBLite)
	library(DBI)
	library(dplyr)
	dbdir <- file.path(tempdir(), "dplyrdir")
	my_db <- src_monetdb(embedded=dbdir)

	my_iris <- copy_to(my_db, iris)
	# Error in .local(conn, name, value, ...) : 
	  # Failed to insert data: MALException:embedded:Could not find table iris
	# In addition: Warning message:
	# In .local(conn, name, value, ...) :
	  # Ignoring csvdump setting in embedded mode
	my_iris <- copy_to(my_db, iris)
	# Error: Table iris already exists.

**Comment by ajdamico** [comment]
using today's dev version

**Comment by hannesmuehleisen** [comment]
indeed that should not happen. Also, library(MonetDBLite) is not necessary here, `MonetDBLite::src_monetdb()` should be enough.

**Comment by ajdamico** [comment]
once this is fixed, please uncomment these two lines in /man/src_monetdb.Rd --

	# # # my_iris <- copy_to(my_db, iris)
	# Then reference a tbl within that src
	# # # my_tbl <- tbl(my_db, "my_iris")

**Comment by hannesmuehleisen** [comment]
ok confirmed.

**Comment by hannesmuehleisen** [comment]
`copy_t` has a parameter `temporary` which defaults to `FALSE`. It works if its set to `TRUE`. But obviously it should not depend on this.

**Comment by ajdamico** [comment]
i would win gold in the breaking shit olympics
