### ISSUE TITLE
plan to leave `mc` and `mq` for external mserver or switch them over to embedded/lite?

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#38]
if you want to switch, these three blocks would need changes

https://github.com/hannesmuehleisen/MonetDBLite/blob/master/R/dbi.R#L28-L40
https://github.com/hannesmuehleisen/MonetDBLite/blob/master/man/mc.Rd
https://github.com/hannesmuehleisen/MonetDBLite/blob/master/man/mq.Rd

**Comment by hannesmuehleisen** [comment]
perhaps add a new one, `ml` and remove `mq` since I think nobody used it anyway?

**Comment by ajdamico** [comment]
will do

**Comment by ajdamico** [comment]
added a barebones ml function here, not sure if you wanted to set defaults though
https://github.com/hannesmuehleisen/MonetDBLite/pull/35/commits/90493359b18e1c72d9a9896a3de1cd00ba4f8aa1

**Comment by hannesmuehleisen** [comment]
looks fine it will default to tempdir.
