### ISSUE TITLE
installs but does not work on windows

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#4]
> library(MonetDBLite)
> library(MonetDB.R)
> library(DBI)
> 
> db <- dbConnect( MonetDBLite() )
Error in .Call("monetdb_startup_R", dir, quiet, getOption("monetdb.squential",  : 
  "monetdb_startup_R" not available for .Call() for package "libmonetdb5"

**Comment by hannesmuehleisen** [comment]
Can you give the full output of install_devtools?

**Comment by ajdamico** [comment]
> devtools::install_github( "hannesmuehleisen/MonetDBLite" )
Downloading GitHub repo hannesmuehleisen/MonetDBLite@master
from URL
https://api.github.com/repos/hannesmuehleisen/MonetDBLite/zipball/master
Installing MonetDBLite
"C:/PROGRA~1/R/R-32~1.5/bin/x64/R" --no-site-file --no-environ --no-save
--no-restore --quiet CMD INSTALL  \

"C:/Users/anthonyd/AppData/Local/Temp/Rtmpg5TntB/devtools22f025d42a95/hannesmuehleisen-MonetDBLite-c993bc3"
--library="C:/Users/anthonyd/Documents/R/win-library/3.2" --install-tests

* installing *source* package 'MonetDBLite' ...
src/acout.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/buildtools/conf/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/buildtools/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/common/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/common/options/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/common/stream/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/common/stream/monetdb-stream.pc.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/common/utils/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/embedded/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/embedded/windows/monetdb_config.h.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/gdk/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/gdk/monetdb-gdk.pc.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/mal/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/mal/mal/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/mal/modules/atoms/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/mal/modules/kernel/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/mal/modules/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/mal/modules/mal/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/mal/optimizer/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/mal/scheduler/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/mal/tools/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/mal/tools/monetdb5.pc.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/monetdb_config.h.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/sql/backends/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/sql/backends/monet5/generator/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/sql/backends/monet5/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/sql/common/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/sql/include/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/sql/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/sql/scripts/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/sql/server/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/sql/storage/bat/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
src/sql/storage/Makefile.in
sed: couldn't open file src/tools/embedded/windows/sedscript: No such file
or directory
> download.file('http://dev.monetdb.org/Assets/R/misc/msvcr100-64.dll',
'src/embedded/windows/msvcr100.dll', mode='wb')
trying URL 'http://dev.monetdb.org/Assets/R/misc/msvcr100-64.dll'
Content type 'application/octet-stream' length 829264 bytes (809 KB)
==================================================
downloaded 809 KB

>
>
> setwd('src/embedded/windows/'); tf <- tempfile(); download.file('
http://dev.monetdb.org/Assets/R/misc/pcre-8.37.zip', tf, mode='wb');
unzip(tf)
trying URL 'http://dev.monetdb.org/Assets/R/misc/pcre-8.37.zip'
Content type 'application/zip' length 174489 bytes (170 KB)
==================================================
downloaded 170 KB

>
>
make: *** No targets.  Stop.
** libs
Warning: this package has a non-empty 'configure.win' file,
so building only the main architecture

installing to
C:/Users/anthonyd/Documents/R/win-library/3.2/MonetDBLite/libs/x64
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (MonetDBLite)
> library(DBI)
> library(MonetDB.R)
> library(MonetDBLite)
> db <- dbConnect( MonetDBLite() )
Error in .Call("monetdb_startup_R", dir, quiet,
getOption("monetdb.squential",  :
  "monetdb_startup_R" not available for .Call() for package "libmonetdb5"
>

**Comment by ajdamico** [comment]
r 3.3.0 needed
