### ISSUE TITLE
should these `dbWriteTable` calls behave the same way?

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#46]
library(nycflights13)
	library(DBI)

	sqlite_dir <- tempfile()
	sqlite_con <- dbConnect( RSQLite::SQLite() , sqlite_dir )

	monetdb_dbdir <- tempdir()
	monetdb_con <- dbConnect(MonetDBLite::MonetDBLite(), embedded = monetdb_dbdir)

	# fails
	dbWriteTable( sqlite_con , "flights" , flights )
	# succeeds
	dbWriteTable( monetdb_con , "flights" , flights )

	> dbWriteTable( sqlite_con , "flights" , flights )
	Error in (function (classes, fdef, mtable)  : 
	  unable to find an inherited method for function ‘dbWriteTable’ for signature ‘"SQLiteConnection", "character", "tbl_df"’
	
	> dbWriteTable( monetdb_con , "flights" , flights )
	Identifier(s) "year", "month", "day", "hour", "minute" are reserved SQL keywords and need(s) to be quoted in queries.
	[1] TRUE

**Comment by hannesmuehleisen** [comment]
i think its good that we support more
