### ISSUE TITLE
should these `dbRemoveTable` failures behave the same way?

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#47]
library(DBI)

	sqlite_dir <- tempfile()
	sqlite_con <- dbConnect( RSQLite::SQLite() , sqlite_dir )

	monetdb_dbdir <- tempdir()
	monetdb_con <- dbConnect(MonetDBLite::MonetDBLite(), embedded = monetdb_dbdir)

	dbRemoveTable( sqlite_con , 'x' )
	# Error in sqliteSendQuery(con, statement, bind.data) : 
	  # error in statement: no such table: x

	# returns FALSE
	dbRemoveTable( monetdb_con , 'x' )

**Comment by hannesmuehleisen** [comment]
we can do that

**Comment by hannesmuehleisen** [comment]
https://github.com/hannesmuehleisen/MonetDBLite/commit/795026f59d96afccfe979c2e9f1e6fe861bf881e
