### ISSUE TITLE
are these transactional commands working as expected?

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#52]
sorry if i'm misunderstanding transactional commands..  thanks

	library(DBI)
	dbdir <- tempdir()
	con <- dbConnect(MonetDBLite::MonetDB(), embedded = dbdir)

	# mtcars has 32 records
	nrow(mtcars)

	dbWriteTable(con, "mtcars", mtcars)
	dbGetQuery(con, "SELECT COUNT(*) FROM mtcars")
	dbListTables(con)
	dbBegin(con)

	# 32+32=64
	dbWriteTable(con, "mtcars", mtcars,append=TRUE)
	# correct nrow
	dbGetQuery(con, "SELECT COUNT(*) FROM mtcars")

	# undo
	dbRollback(con)

	# why is this not 32?
	dbGetQuery(con, "SELECT COUNT(*) FROM mtcars")

	# should these two lines return errors
	# since they are not prefaced by a dbBegin()?
	dbCommit(con)
	dbRollback(con)

	# why is this not 32?
	dbGetQuery(con, "SELECT COUNT(*) FROM mtcars")

**Comment by hannesmuehleisen** [comment]
`dbWriteTable` has a flag `transaction` that needs to be set to `FALSE` if it should be used inside a transaction. It defaults to `TRUE`.

**Comment by ajdamico** [comment]
weird, thanks.  isn't that upside-down?

**Comment by hannesmuehleisen** [comment]
dbwritetable already uses a transaction to make sure the table is either fully imported or not at all this is why if we have a transaction around it we need to tell it

**Comment by ajdamico** [comment]
could the method figure out whether it's already inside a transaction and just behave appropriately?

**Comment by hannesmuehleisen** [comment]
yes :P

**Comment by ajdamico** [comment]
hahaha i'm gonna open an issue for maybe milestone 2.0.0.  github won't let me set to enhancement but it obvi is
