### ISSUE TITLE
please remove need for transaction= parameter/flag for dbWriteTable method

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#53]
discussion here..
https://github.com/hannesmuehleisen/MonetDBLite/issues/52#issuecomment-225126757

**Comment by hannesmuehleisen** [comment]
yeah we have to export that state from the backend somehow

**Comment by hannesmuehleisen** [comment]
also dbWriteTable should not commit your transaction if you had one...

**Comment by hannesmuehleisen** [comment]
problem on monetdb mapi connections, no direct way to find out whether a transaction had been started.

**Comment by hannesmuehleisen** [comment]
should be fixed

**Comment by ajdamico** [comment]
great, thank you

**Comment by ajdamico** [comment]
i will add a testthat

**Comment by hannesmuehleisen** [comment]
there are some test cases for this already?

**Comment by ajdamico** [comment]
yep, and cleaner than what i would have added.  thanks for this
