### ISSUE TITLE
example in documentation 'MonetDB.R' fails to run

### ISSUE THREAD

**Issue by HanOostdijk** [hannesmuehleisen/MonetDBLite#59]
Looking for an example to use the package I viewed the list of functions in the documentation and tried to use the code in the example for `MonetDB.R`.  Processing did hang on 
`con <- dbConnect(MonetDBLite::MonetDB.R(), dbname = "demo")`. 
Reading the full info (what I normally try to avoid at all costs) I saw in the text that the function  `MonetDB.R` is deprecated in favor of `MonetDBLite`. Changing `MonetDB.R`to `MonetDBLite` solved my problem. 

Because `MonetDB.R` apparently is not only deprecated but does not work anymore (in my environment at least, see below) I think that future new users would benefit from the removal of this documentation entry and moving the nice usage example to `MonetDBLite`.

My environment (part of sessionInfo output):

```
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

[1] DBI_0.4-1         MonetDBLite_0.3.1
```

**Comment by ajdamico** [comment]
hi @HanOostdijk do you have an *external* mserver session running?  `?MonetDB.R` specifies this..

**Comment by ajdamico** [comment]
hi @hannesmuehleisen the code in `?MonetDBLite::MonetDB.R` does not hang if you have an external mserver open, but it does break immediately.  and if an external mserver is not available, then @HanOostdijk is right that it hangs when it should simply fail without `wait=TRUE`


	> library(DBI)
	> con <- dbConnect(MonetDBLite::MonetDB.R(), dbname = "demo")
	> con
	<MonetDBConnection>
	Warning messages:
	1: In value[[3L]](cond) :
	  "mapi_split" not available for .Call() for package "libmonetdb5"
	2: Pending rows 
	> dbWriteTable(con, "iris", iris)
	Identifier(s) "Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species" contain uppercase or reserved SQL characters and need(s) to be quoted in queries.
	[1] TRUE
	Warning messages:
	1: In value[[3L]](cond) :
	  "mapi_split" not available for .Call() for package "libmonetdb5"
	2: Pending rows 
	3: In value[[3L]](cond) :
	  "mapi_split" not available for .Call() for package "libmonetdb5"
	4: Pending rows 
	> dbListTables(con)
	character(0)
	Warning messages:
	1: In value[[3L]](cond) :
	  "mapi_split" not available for .Call() for package "libmonetdb5"
	2: Pending rows 
	> dbGetQuery(con, "SELECT COUNT(*) FROM iris")
	NULL
	Warning messages:
	1: In value[[3L]](cond) :
	  "mapi_split" not available for .Call() for package "libmonetdb5"
	2: Pending rows 
	> d <- dbReadTable(con, "iris")
	Error in dbReadTable(con, "iris") : Unknown table: iris
	In addition: Warning messages:
	1: In value[[3L]](cond) :
	  "mapi_split" not available for .Call() for package "libmonetdb5"
	2: Pending rows 
	>

**Comment by HanOostdijk** [comment]
Anthony,

I saw your article (as relayed on http://www.r-bloggers.com/monetdblite-because-fast/ ; my browser warns me not to access ``http://www.asdfree.com/2016/06/monetdblite-because-fast.html`` because it is **harmful** ??) . Extract: 

> MonetDBLite is a SQL database that runs inside the R environment for statistical computing and does not require the installation of any external software. MonetDBLite is based on free and open-source MonetDB, a product of the Centrum Wiskunde & Informatica.

I was attracted by the no-installation part: therefore **no server**.
While typing I saw in your new message that you could recreate the 'problem'.

**Comment by ajdamico** [comment]
hi @HanOostdijk thanks, but please e-mail me directly about this and delete your comment, it is not relevant to the current bug report..thanks  :)

**Comment by hannesmuehleisen** [comment]
wait why are these errors happening?

**Comment by ajdamico** [comment]
open up an mserver session and then run..

    library(DBI)
    con <- dbConnect(MonetDBLite::MonetDB.R(), dbname = "demo")
    con

**Comment by hannesmuehleisen** [comment]
this is a bug

**Comment by hannesmuehleisen** [comment]
works for me
