### ISSUE TITLE
MonetDBLite instalation is breakin

### ISSUE THREAD

**Issue by DjalmaPessoa** [hannesmuehleisen/MonetDBLite#62]
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 10586)

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252   
[3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                      
[5] LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
> devtools::install_github("hannesmuehleisen/MonetDBLite")
Downloading GitHub repo hannesmuehleisen/MonetDBLite@master
from URL https://api.github.com/repos/hannesmuehleisen/MonetDBLite/zipball/master
Installing MonetDBLite
"C:/PROGRA~1/R/R-33~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/owner/AppData/Local/Temp/RtmpEndFj9/devtools13082ca14a56/hannesmuehleisen-MonetDBLite-0564406"  \
  --library="C:/Users/owner/Documents/R/win-library/3.3" --install-tests 

ERROR: failed to lock directory 'C:/Users/owner/Documents/R/win-library/3.3' for modifying
Try removing 'C:/Users/owner/Documents/R/win-library/3.3/00LOCK-hannesmuehleisen-MonetDBLite-0564406'
Erro: Command failed (3)

**Comment by hannesmuehleisen** [comment]
"Try removing 'C:/Users/owner/Documents/R/win-library/3.3/00LOCK-hannesmuehleisen-MonetDBLite-0564406'" ?

**Comment by DjalmaPessoa** [comment]
I've done it and it is running for a quite a while...

On Thu, Jun 30, 2016 at 12:28 PM, Hannes Mühleisen <notifications@github.com

**Comment by hannesmuehleisen** [comment]
yes compilation takes a while

**Comment by DjalmaPessoa** [comment]
Thanks. I'll be waiting.

On Thu, Jun 30, 2016 at 12:39 PM, Hannes Mühleisen <notifications@github.com

**Comment by hannesmuehleisen** [comment]
did this work in the end?

**Comment by hannesmuehleisen** [comment]
assuming this to work now
