### ISSUE TITLE
Issues reading .csv file into a dplyr connection

### ISSUE THREAD

**Issue by TaylorAndrew** [hannesmuehleisen/MonetDBLite#64]
Connecting using the dplyr connection, so I can use dplyr with the tables 

    dbdir <- file.path(tempdir(), "dplyrdir")
    my_db <- MonetDBLite::src_monetdb(embedded=dbdir)

Copying a local dataframe per the example:

    my_iris <- copy_to(my_db, iris)
    my_iris %>% filter(Species == 'setosa') %>%  summarise(mean(Sepal.Length))

Sorry, there was really no reason to show that. It works. 

I don't actually see a use case for the above. But I love the idea of MonetDBLite. I want to pull a large .csv off my drive and into the temp sql server. 

     loan <- monetdb.read.csv(my_db, 'C:/path/to/lending/club/loan.csv', "loans")

Error:

    Error in (function (classes, fdef, mtable):  unable to find an inherited method for function ‘dbBegin’ for signature ‘"src_monetdb"’

Is this a bug or is there some string of `MonetDBLite`, `MonetDB.R`, `DBI`, `dplyr` string of  commands that I can run to 

1) Pull .csv files into my MonetDBLite connection
2) Use dplyr to manipulate said tables

Thanks. Great talk at useR and I really think MonetDBLite is going to become a large part of my workflow.

**Comment by ajdamico** [comment]
hi, if you create `my_db` this way instead, does the `monet.read.csv` line work?

    my_db <- dbConnect( MonetDBLite::MonetDBLite() , dbdir )

**Comment by TaylorAndrew** [comment]
Yes and No. I no longer get the connection error, but `monetdb.read.csv()` is failing to read the data. Using the [lending club loans data](https://www.kaggle.com/wendykan/lending-club-loan-data) on kaggle, the following error is provided. 

    Identifier(s) "desc" are reserved SQL keywords and need(s) to be quoted in queries.
    Error in .local(conn, statement, ...) : 
      Unable to execute statement 'COPY OFFSET 2 INTO loans FROM 'C:\\Users\\taylo\\Documents\\Datasets\\loan.csv' USING DELIMITERS ','...'.
    Server says 'SQLException:importTable:Failed to import table line 42539 field 51 'boolean' expected in '53.0''.


This data is able to get pulled into Spark with `sparklyr::spark_read_csv()` and R with `read.csv`, so I feel like this is a bug

**Comment by ajdamico** [comment]
thanks!  that part looks less like a bug and more like a product of MonetDB's strictness. you can use `best.effort = TRUE` but it will toss the rows that aren't the expected column types.  you could also increase your `nrow.check` parameter to 100000.  if you still disagree, then please provide a minimal reproducible example


the question for @hannesmuehleisen here is whether or not something with this class (rather than a simple MonetDBLite connection) should be accepted as the connection parameter of `monet.read.csv`

    class(my_db)
    [1] "src_monetdb" "src_sql"     "src"

**Comment by TaylorAndrew** [comment]
Yeah, I'm getting more and more confused here.

If I take the dplyr solution you guys provide (recopied from above):

    dbdir <- file.path(tempdir(), "dplyrdir")
    my_db <- MonetDBLite::src_monetdb(embedded=dbdir)
    my_iris <- copy_to(my_db, iris)
    my_iris %>% filter(Species == 'setosa') %>%  summarise(mean(Sepal.Length))

I can assign a name to the connection to iris in monetdblite, and then use dplyr's arguments and piping to manipulate the data in MonetDBLite


But when I now use `dbConnect()` as you suggest:

    my_db <- dbConnect( MonetDBLite::MonetDBLite() , dbdir )

And then run `monetdb.read.csv()` in a similar fashion:

    loan <- monetdb.read.csv(my_db, 'C:/Users/taylo/Documents/Datasets/loan.csv', "loans",
                         best.effort = T) #This works, though I didn't check to see table size, but it doesn't throw any errors

`loan` is null. Thus, it isn't creating a link to that table in the same way `dplyr::copy_to()` works.


So, back to my original question:

Is there any workflow with MonetDBLite that 

1) Can read in .csv files
2) Use dplyr to work with those files


Sorry to be a pain. I'm trying to navigate through the package but there seem to be many functions, some examples don't work, some functions don't seem to work together, deprecated functions and  many very similarly named functions. Not complaining, as I know it's very much still in development. But I'm just finding it hard to work my way through the documentation on my own to find the correct solutions. 

If the lack of a connection object in `monetdb.read.csv()` that is "`dplyr` available" isn't a bug, I will close this and open a new issue that can be more clearly labeled as an 'enhancement'

**Comment by ajdamico** [comment]
what step in this (passing) workflow[1] are you missing?  you can create the src_monetdb after the table has been read into the database through `monet.read.csv` and then access the table as normal.  i agree that you should open a separate feature request.  thanks

[1] https://github.com/hannesmuehleisen/MonetDBLite/blob/master/tests/testthat/test_03_dplyr.R

**Comment by hannesmuehleisen** [comment]
`dplyr` wraps the `DBI` connection, if you want to use a DBI function like `dbWriteTable` or `monetdb.read.csv` with a `dplyr` `src` or `tbl` you need to grab the connection from them as follows:

```
library(DBI)
library(dplyr)
s <- MonetDBLite::src_monetdblite()
dbWriteTable(s$con, "mtcars", mtcars)
t <- tbl(s, "mtcars")
dbListTables(t$src$con)
```

A cleaner way to do this is to manually create the connection and keep a reference:
```
con <- dbConnect(MonetDBLite::MonetDBLite())
s <- MonetDBLite::src_monetdblite(con=con)
dbWriteTable(con, "mtcars", mtcars)
t <- tbl(s, "mtcars")
ddbListTables(con)
```
