### ISSUE TITLE
unrealistic processing times for basic commands

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#68]
reproducible speed test slowness..  both the monetdb_load and the monetdb_sum timing columns are absurd.  something is hanging (might be monetdb and not lite)

http://homepages.cwi.nl/~hannes/sisyphus/win-3/1467530217/speed.log
http://homepages.cwi.nl/~hannes/sisyphus/win-3/1467676094/speed.log

the loading also hiccups on unix: loading `10^7` records takes longer than loading `10^8` records.

http://homepages.cwi.nl/~hannes/sisyphus/fedora20-4/1467669464/speed.log
http://homepages.cwi.nl/~hannes/sisyphus/fedora20-4/1467621131/speed.log

thanks

**Comment by hannesmuehleisen** [comment]
performance measurements on those boxes dont make a lot of sense since they are clogged up a lot

**Comment by ajdamico** [comment]
after testing on rocks040 and two separate windows machines, i think you are right :)  thanks
