### ISSUE TITLE
the 64 simultaneous connections limit counts connections even after dbDisconnect

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#70]
```
library(DBI)

for( j in 1:100 ){

    db <- dbConnect( MonetDBLite::MonetDBLite() )
    dbWriteTable( db , 'mtcars' , mtcars , append = TRUE )
    dbDisconnect( db , shutdown = TRUE )

}
# Error in monetdb_embedded_startup(embedded, !getOption("monetdb.debug.embedded",  : 
  # Failed to initialize embedded MonetDB Failed to initialize client
j
# [1] 64
```

**Comment by hannesmuehleisen** [comment]
good catch!

**Comment by ajdamico** [comment]
should subtract one when shutdown=FALSE and reset to zero when
shutdown=TRUE i think?

**Comment by ajdamico** [comment]
the 64 `dbConnect` limit appears to be session-wide.  two separate databases still fail after 32 startups each

	library(DBI)

	td1 <- paste0( tempdir() , "/one" )
	td2 <- paste0( tempdir() , "/two" )


	for( j in 1:50 ){

		conn <- dbConnect( MonetDBLite::MonetDBLite() , td1 )

		dbDisconnect( conn , shutdown = TRUE )

		conn <- dbConnect( MonetDBLite::MonetDBLite() , td2 )

		dbDisconnect( conn , shutdown = TRUE )

	}


	# Error in monetdb_embedded_startup(embedded, !getOption("monetdb.debug.embedded",  : 
	  # Failed to initialize embedded MonetDB Failed to initialize client

	j
	# [1] 32

**Comment by ajdamico** [comment]
error message here should also specify the problem, if not too much extra trouble?  thanks homeslice

**Comment by hannesmuehleisen** [comment]
its not the connections i think

**Comment by hannesmuehleisen** [comment]
fixed in Dec2016Lite-R branch

**Comment by ajdamico** [comment]
thanks again
