### ISSUE TITLE
inconsistent append=TRUE behavior from data.frame vs csv with dbWriteTable

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#73]
should `append=TRUE` always succeed or always fail if the table didn't exist in the first place?  with `RSQLite`, it always succeeds.

	library(DBI)
	conn <- dbConnect( MonetDBLite::MonetDBLite() )

	tf <- tempfile()
	write.csv( mtcars , tf , row.names = FALSE )

	# fails
	dbWriteTable( conn , 'mtcars' , tf , append = TRUE )

	# works
	dbWriteTable( conn , 'mtcars' , mtcars , append = TRUE )

**Comment by hannesmuehleisen** [comment]
yes this should be consistent

**Comment by ajdamico** [comment]
thanx
