### ISSUE TITLE
Performance when loading large datasets

### ISSUE THREAD

**Issue by pjtatlow** [hannesmuehleisen/MonetDBLite#74]
I'm loading a large biological dataset into a MonetDBLite table, and I've noticed that I can query the data very quickly (instantly) when I'm only selecting a few columns, but when I `SELECT * FROM 'table' WHERE ...` and load all 22,000+ columns in, performance takes a huge hit (several minutes). All I need to do though is write this data to a file, and I'm wondering if loading all the data into a data frame is responsible for the drastic decrease in performance and if there is any way to avoid it. Thanks!

**Comment by ajdamico** [comment]
hi, that's how column store databases work ;)  consider copying your monetdblite table directly into an external file?  https://www.monetdb.org/Documentation/Manuals/SQLreference/CopyInto

**Comment by hannesmuehleisen** [comment]
Thanks @ajdamico that is indeed the correct solution here.
