### ISSUE TITLE
Warning instead of error for `na.rm` 

### ISSUE THREAD

**Issue by cronacronis** [hannesmuehleisen/MonetDBLite#76]
`Error: na.rm not needed in SQL: NULL are always dropped`

Would it be possible to change `error` to `warning` in order to keep compatibility with R legacy code?

**Comment by ajdamico** [comment]
could you provide a minimal reproducible example?

**Comment by cronacronis** [comment]
```
library(data.table)
library(MonetDBLite)
library(DBI)
dbdir = "/home/cracs/repos/git/analysisengine/monetdblite"
con <- dbConnect(MonetDBLite::MonetDBLite(), dbdir)
## dbRemoveTable(con, "dt_mtcars")
dbWriteTable(con, "dt_mtcars", dt_mtcars)

library(dplyr)
ms <- MonetDBLite::src_monetdblite(dbdir = dbdir)
mt <- tbl(ms, "dt_mtcars")
mt %>% filter(d_year == 2013) %>% group_by(dest) %>% summarise(max(cyl_na, na.rm = TRUE)) %>% collect %>% data.table
```

Will produce `Error: na.rm not needed in SQL: NULL are always dropped`

**Comment by ajdamico** [comment]
hello, this is `dplyr` behavior, not `MonetDBLite`.  you'll need to move this conversation to the maintainers of dplyr if you'd like to suggest a change..thanks

	tf <- tempfile()

	library(DBI)
	con <- dbConnect(RSQLite::SQLite(),tf)
	dbWriteTable(con, "mtcars", mtcars)

	library(dplyr)
	ms <- src_sqlite(tf)
	mt <- tbl(ms, "mtcars")
	mt %>% summarise(max(cyl, na.rm = TRUE))

**Comment by cronacronis** [comment]
You are right, sorry for bringing it up here.
https://github.com/hadley/dplyr/blob/master/R/translate-sql-helpers.r#L117
