### ISSUE TITLE
a monetdblite database directory can be non-UTF-8, but the COPY INTO file path cannot

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#82]
not sure if you think this is a MonetDBLite problem, a monetdb problem, or a non-problem  :)

```
library(MonetDBLite)
library(DBI)

# breaks
tf <- paste0( tempfile() , "Mühleisen" )
db <- dbConnect( MonetDBLite() )
write.csv( mtcars , tf )
monetdb.read.csv( db , tf , 'mtcars2' )
# error.

# surprisingly it's only the monetdb.read.csv.
# having the ü in the database directory is fine.
dbDisconnect( db , shutdown = TRUE )
td <- paste0( tempdir() , "Mühleisen" )
db <- dbConnect( MonetDBLite() , td )
dbWriteTable( db , 'mtcars' , mtcars )
dbReadTable( db , 'mtcars' )
```

**Comment by hannesmuehleisen** [comment]
what's the error?

**Comment by hannesmuehleisen** [comment]
This should work.

**Comment by ajdamico** [comment]
Identifier(s) "X" contain uppercase or reserved SQL characters and need(s) to be quoted in queries.
Error in .local(conn, statement, ...) : 
  Unable to execute statement 'COPY OFFSET 2 INTO mtcars2 FROM 'C:\\Users\\anthonyd\\AppData\\Local\\Temp\\RtmpOMlHfI\\file1b9034b2...'.
Server says 'ParseException:SQLparser:!invalid continuation in UTF-8 sequence'.

**Comment by hannesmuehleisen** [comment]
we could change encodings to utf on all queries

**Comment by ajdamico** [comment]
in the situation above, it might be more informative for the user if it just breaks noisily?  coercing the query to utf-8 could potentially create a separate db folder?  but i don't feel strongly

**Comment by hannesmuehleisen** [comment]
well this is already complaining, the same would happen if the encoded special char would be elsewhere in the query. so not sure what i should do about it

**Comment by ajdamico** [comment]
but not consistently.  if it always complained, the second block would also break.

**Comment by hannesmuehleisen** [comment]
always converting all query text to UTF now the way monet likes it anyway
