### ISSUE TITLE
MonetdbLite embebed R functions

### ISSUE THREAD

**Issue by gfmartins** [hannesmuehleisen/MonetDBLite#85]
I'm trying to use embebed R functions like:

```
CREATE FUNCTION rapi00() RETURNS TABLE (d INTEGER) LANGUAGE R {
    seq(1,10);
};
```

I think that it creates the function:
Server says 'ParseException:SQLparser:CREATE FUNCTION: name 'rapi00' already in use'.

however when I do the 'select', it says:
```
Unable to execute statement 'SELECT d FROM rapi00() AS r WHERE d > 5'.
Server says 'SQLException:SQLparser:Errors encountered in query'.
```

Does monetDBlite supports the creation of custom functions?

**Comment by hannesmuehleisen** [comment]
MonetDBLite does not support embedded R functions. Why would you want to have those?

**Comment by gfmartins** [comment]
thank you.
I tried to see if that would work. I'm trying to manipulate/transform data on "select" with custom functions. 

You are right, maybe better to do that outside of monet.
