### ISSUE TITLE
32 bit windows monetdblite install fails

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#87]
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
	Copyright (C) 2016 The R Foundation for Statistical Computing
	Platform: i386-w64-mingw32/i386 (32-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	> install.packages("MonetDBLite")
	Installing package into ‘C:/Users/AnthonyD/Documents/R/win-library/3.3’
	(as ‘lib’ is unspecified)
	--- Please select a CRAN mirror for use in this session ---
	Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘MonetDBLite’
	  These will not be installed
	>

**Comment by ajdamico** [comment]
once 32 bit works, we could remove this `if()` block

https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-extract_svygini.R#L57-L59

**Comment by ajdamico** [comment]
removed already, why not  https://github.com/DjalmaPessoa/convey/commit/654a03d35d7dbeccec0e731295903a6ba45d8c40

**Comment by hannesmuehleisen** [comment]
Emailed Uwe Ligges on the topic

**Comment by hannesmuehleisen** [comment]
Will be fixed within 48h through CRAN rebuilds

**Comment by ajdamico** [comment]
thanks
