### ISSUE TITLE
repeated appends cause windows error (not crash) with low memory

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#88]
used today's version of Dec2016Lite-R

tried twice, crashed twice.  first crash, `i = 607`.  second crash (below) `i = 571`..

	Microsoft Windows [Version 10.0.10586]
	(c) 2015 Microsoft Corporation. All rights reserved.

	C:\Users\anthonyd>"C:\Program Files\R\R-3.3.2\bin\x64\Rterm.exe" --max-mem-size=35M

	R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
	Copyright (C) 2016 The R Foundation for Statistical Computing
	Platform: x86_64-w64-mingw32/x64 (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	>
	>
	> library(DBI)
	> db <- dbConnect( MonetDBLite::MonetDBLite() )
	> for( i in 1:1000 ) { dbWriteTable( db , 'x' , mtcars , append = TRUE ) }
	Error in if (dbGetQuery(conn, paste0("select count(*) as is_tmp_schema from sys.tables join sys.schemas on tables.schema_id=schemas.id where tables.name='",  :
	  argument is of length zero
	> dbDisconnect( db , shutdown = TRUE )
	[1] TRUE
	>
	> i
	[1] 571
	>
	

comparable RSQLite code worked without issue
	
	library(DBI)
	db <- dbConnect( RSQLite::SQLite() )
	for( i in 1:1000 ) { dbWriteTable( db , paste0( 'x' , i ) , mtcars , append = TRUE ) }

**Comment by ajdamico** [comment]
please consider moving this up to `0.3.2`.  aside from internet hiccups, 100% of the errors on sisyphus are caused by this.  thanks

**Comment by hannesmuehleisen** [comment]
your wish is my command

**Comment by ajdamico** [comment]
haha sorry, i know it's a horrible bug.  but all the other fixes are small potatoes in comparison.  the segfaults hold MonetDBLite back from the greatness it deserves  ;)

**Comment by ajdamico** [comment]
today's dev version: 2 passes, 2 segfaults, 4 errors

![status](https://cloud.githubusercontent.com/assets/216807/21716637/99879518-d3d9-11e6-9b41-789a3f270797.png)

**Comment by ajdamico** [comment]
duplicate of https://github.com/hannesmuehleisen/MonetDBLite/issues/115
