### ISSUE TITLE
connect append disconnect cause BBPdir error (not crash)

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#89]
used today's version of Dec2016Lite-R

tried five times, crashed at `i = 253` every time (seems perfectly reproducible).

unrelated to RAM ceilings:

	Microsoft Windows [Version 10.0.10586]
	(c) 2015 Microsoft Corporation. All rights reserved.

	C:\Users\anthonyd>"c:\Program Files\r\R-3.3.2\bin\x64\Rterm.exe"

	R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
	Copyright (C) 2016 The R Foundation for Statistical Computing
	Platform: x86_64-w64-mingw32/x64 (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	> library(DBI)
	> for( i in 1:254 ) {
	+ db <- dbConnect( MonetDBLite::MonetDBLite() )
	+ dbWriteTable( db , 'x' , mtcars , append = TRUE )
	+ dbDisconnect( db , shutdown = TRUE )
	+ }
	Error in monetdb_embedded_startup(embedded, !getOption("monetdb.debug.embedded",  :
	  Failed to initialize embedded MonetDB !FATAL: BBPdir: subcommit attempted without backup BBP.dir.
	>
	> i
	[1] 253
	>

	

sort of comparable RSQLite code worked without issue..  but there's no db shutdown
	
	
	library(DBI)
	for( i in 1:1000 ) { 
		db <- dbConnect( RSQLite::SQLite() )
		dbWriteTable( db , 'x' , mtcars , append = TRUE )
		# dbDisconnect( db , shutdown = TRUE )
	}

**Comment by hannesmuehleisen** [comment]
something is going on here, yes. investigating.

**Comment by ajdamico** [comment]
fwiw, the `dbWriteTable()` is likely irrelevant?

if you are able to solve this, you likely will also solve https://github.com/hannesmuehleisen/MonetDBLite/blob/master/tests/testthat/test_05_ram.R#L9

the single_restarts function also dies at `i=253` but with a different error message:

	single startup and shutdown iteration 252 
	Error in readRDS(res) : error reading from connection

**Comment by ajdamico** [comment]
travis looks like this is not fixed?  :/

**Comment by hannesmuehleisen** [comment]
travis has different issue i think

**Comment by ajdamico** [comment]
ok.  not sure if this matters, but the readRDS() crash is the same error i
get locally on the shutdown/restarts
