### ISSUE TITLE
C function monetdb_error_R only returns the first line of the mserver error

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#93]
minimal reproducible example below that prints only the mserver text "incompatible BBP version: expected 061033, got 060650."

	# Error in monetdb_embedded_startup(embedded, !getOption("monetdb.debug.embedded",  : 
	  # Failed to initialize embedded MonetDB !FATAL: BBPinit: incompatible BBP version: expected 061033, got 060650.
	  
however, according to lines 1227-1230 of monetdb, it should actually print four lines  https://github.com/hannesmuehleisen/MonetDBLite/blob/91b728a87b006c300d8ba1cc42dcdaef2a765469/src/gdk/gdk_bbp.c#L1227-L1230

	library(DBI)
	db <- dbConnect( MonetDBLite::MonetDBLite() )
	dbDisconnect( db , shutdown = TRUE )
	bbpfn <- paste0( tempdir() , "/bat/BACKUP/BBP.dir" )
	bbpdir <- readLines( bbpfn )
	bbpdir <- gsub( "GDKversion 25115" , "GDKversion 25000" , bbpdir )
	writeLines( bbpdir , bbpfn )
	db <- dbConnect( MonetDBLite::MonetDBLite() )

i believe this can be fixed by editing these six lines of code with something equivalent to a `paste( res , collapse="\n" )` command, but it's C code so i'm not sure

https://github.com/hannesmuehleisen/MonetDBLite/blob/2be66fbfdca169ab8d07671bdd4ca100f147a325/src/embedded/embeddedr.c#L40-L45

**Comment by hannesmuehleisen** [comment]
This works fine for me. Windows only issue?

**Comment by hannesmuehleisen** [comment]
removed the newline in the error

**Comment by ajdamico** [comment]
in all server errors and notifications, right?  this was just an example of
multiline error truncation

**Comment by hannesmuehleisen** [comment]
yes all errors

**Comment by ajdamico** [comment]
thanks holmes
