### ISSUE TITLE
dbGetRowCount method does not work

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#95]
library(DBI)

	# sqlite example mostly taken from ?dbGetRowCount

	sqlite_con <- dbConnect(RSQLite::SQLite(), ":memory:")

	dbWriteTable(sqlite_con, "mtcars", mtcars)

	# Fetch all results
	rs <- dbSendQuery(sqlite_con, "SELECT * FROM mtcars WHERE cyl = 4")
	dbFetch(rs)
	dbClearResult(rs)

	# Fetch in chunks
	rs <- dbSendQuery(sqlite_con, "SELECT * FROM mtcars")
	while (!dbHasCompleted(rs)) {
	  chunk <- dbFetch(rs, 10)
	  
	  # CORRECT RESULT: 10, 20, 30, 32
	  print(dbGetRowCount(rs))
	  
	}

	dbClearResult(rs)
	dbDisconnect(sqlite_con)

	
	
	# same example with incorrect results highlighted below
	

	monetdb_con <- dbConnect(MonetDBLite::MonetDBLite())

	dbWriteTable(monetdb_con, "mtcars", mtcars)

	# Fetch all results
	rs <- dbSendQuery(monetdb_con, "SELECT * FROM mtcars WHERE cyl = 4")
	dbFetch(rs)
	dbClearResult(rs)

	# Fetch in chunks
	rs <- dbSendQuery(monetdb_con, "SELECT * FROM mtcars")
	while (!dbHasCompleted(rs)) {
	  chunk <- dbFetch(rs, 10)

	  # INCORRECT RESULT: 32, 32, 32, 32
	  print(dbGetRowCount(rs))
	  
	}

	dbClearResult(rs)
	dbDisconnect(monetdb_con)

**Comment by ajdamico** [comment]
works post merge yes?

**Comment by hannesmuehleisen** [comment]
works yes
