### ISSUE TITLE
dplyr::arrange fails without collect

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite#97]
library(dplyr)
	library(MonetDBLite)

	my_db_sqlite <- src_sqlite(tempfile(), create = T)
	my_db_monetdb <- src_monetdb(embedded=tempdir())

	mtcars_sqlite <- copy_to(my_db_sqlite, mtcars, temporary = FALSE)
	mtcars_monetdb <- copy_to(my_db_monetdb, mtcars, temporary = FALSE)

	# works as expected
	arrange( mtcars , cyl )
	arrange( mtcars_sqlite , cyl )

	# works with collect
	collect( arrange( mtcars_monetdb , cyl ) )
	# but fails without it
	arrange( mtcars_monetdb , cyl )
	# arrange calls
	# sql_subquery.MonetDBConnection
	# which then goes to
	# monetdb_check_subquery()
	# which tests for ORDER BY and triggers the error

**Comment by hannesmuehleisen** [comment]
works now

**Comment by ajdamico** [comment]
should all of the `collect()` calls be removed from the dplyr testthat?
